In [1]:
import numpy as np
import pandas as pd

# ЗАДАЧА № 0

In [3]:
# Получите элементы s1, которые не присутствуют в s2. Функция должна вернуть серию.

In [2]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([4, 5, 6, 7, 8])

In [3]:
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
s2

0    4
1    5
2    6
3    7
4    8
dtype: int64

In [5]:
s1[s1.isin(s2)]

3    4
4    5
dtype: int64

In [6]:
s1[~s1.isin(s2)]

0    1
1    2
2    3
dtype: int64

In [7]:
s1[~np.isin(s1, s2)]

0    1
1    2
2    3
dtype: int64

In [8]:
s1[~np.isin(s2, s1)]

2    3
3    4
4    5
dtype: int64

In [10]:
np.isin(s1, s2)

array([False, False, False,  True,  True])

In [11]:
np.isin(s2, s1)

array([ True,  True, False, False, False])

# ЗАДАЧА №1

In [ ]:
# Создайте новый pandas.Series из элементов, которые присутствуют только в 
# одном из двух pandas.Series (переменные s1, s2).

# Если элемент присутствует в двух Series, то включать его не надо.

In [12]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([4, 5, 6, 7, 8])

In [13]:
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [14]:
s2

0    4
1    5
2    6
3    7
4    8
dtype: int64

In [17]:
s3 = np.union1d(s1,s2)
s3

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [18]:
s4 = np.intersect1d(s1,s2)
s4

array([4, 5], dtype=int64)

In [61]:
# можно так:
s3[~np.isin(s3, s4)]

array([1, 2, 3, 6, 7, 8], dtype=int64)

In [19]:
np.isin(s3, s4)

array([False, False, False,  True,  True, False, False, False])

In [92]:
# можно так:
s3[~s3.isin(s4)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [95]:
# можно так:
s3[~np.isin(s3, np.intersect1d(s1,s2))]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [126]:
# чтобы Stepik принял задание нужно так:

s3 = pd.Series(np.union1d(s1,s2))
s3

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [127]:
s4 = pd.Series(np.intersect1d(s1,s2))
s4

0    4
1    5
dtype: int64

In [130]:
s3[~s3.isin(s4)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [135]:
s3[~np.isin(s3,s4)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

# Задача №2

In [ ]:
# На вход подается pd.Series

# Найти:

# наименьшее значение
# 25 перцентиль
# медиану
# 75 перцентиль
# наибольшее значение
# Все значения должны быть упакованы в серию.

In [20]:
ser = pd.Series([12.539048, 5.688863, 16.247349, 9.601944, 5.551343, 5.591008, 10.093195, 11.189223, 10.067743, 1.822353])

In [21]:
ser

0    12.539048
1     5.688863
2    16.247349
3     9.601944
4     5.551343
5     5.591008
6    10.093195
7    11.189223
8    10.067743
9     1.822353
dtype: float64

In [27]:
minima = np.min(ser)
minima

1.822353

In [28]:
percentile_25 = np.percentile(ser, 25)
percentile_25

5.61547175

In [29]:
mediana = np.median(ser)
mediana

9.8348435

In [30]:
percentile_75 = np.percentile(ser, 75)
percentile_75

10.915216000000001

In [31]:
maxi = np.max(ser)
maxi

16.247349

In [32]:
result = pd.Series([minima, percentile_25, mediana, percentile_75, maxi])
result

0     1.822353
1     5.615472
2     9.834843
3    10.915216
4    16.247349
dtype: float64

In [33]:
# Процентиль - это некая граница, которая делит всю выборку данных на определенные части 
# соглано их частоте повторений. Другими словами, если у нас 100 студентов сдали экзамен 
# с некоторым результатом (5 студентов на отлично, 45 студентов на хорошо, 15 студентов 
# на удовлетворительно, а остальные - на неудовлетворительно), 
# то интерпретация будет такой: 5% студентов сдали на отлично (5% процентиль, т.е. все 
# отличники попали в группу, которая занимает не более 5% от всей выборки. 
# По остальным студентоам аналогично).
# Поэтому, например, 25-я процентиль отсекает данные от общей выборки так, что в
# ней остаются только те данные, что имеют частоту появления ниже 25%. Аналогично 
# и с 75-ой процентилью, которая делит выборку так, что остаются только те данные, 
# что встречаются не более 75%. С медианой (50%) всё аналогично.
# А вот с минимум и максимум могу добавить только то, что наименьшему значению 
# соответствует нулевой процентиль, наибольшему - 100-й процентиль, как в аналогии, 
# что медиане соответствует 50-й процентиль и т.д.

# https://www.youtube.com/watch?v=SaF2G5WMwt   


# Поэтому правильный и локоничный код будет следующим:

np.percentile(ser, [0, 25, 50, 75, 100])

array([ 1.822353  ,  5.61547175,  9.8348435 , 10.915216  , 16.247349  ])

# Задача №3

In [ ]:
# Определите сколько раз встречается каждое значение в исходном pandas.Series (переменная s). 
# Функция должна вернуть серию с подсчитанным количеством каждого символа.

In [33]:
s = pd.Series(list('abdcbdhafceeabcahbcaedadaecbbbecafgh'))

In [34]:
s.value_counts()

a    8
b    7
c    6
e    5
d    4
h    3
f    2
g    1
dtype: int64

# Задача №4

In [2]:
# Доработайте код таким образом, чтобы оставить только 2 наиболее встречающихся значения, а для остальных установите 
# значение 'Yet another value'.

# Функция solution должна возвращать серию.

# Финальный результат, который должен получиться:
# 0                     a
# 1                     b
# 2     Yet another value
# 3     Yet another value
# 4                     b
# .........................

s = pd.Series(list('abdcbdhafceeabcahbcaedadaecbbbecafgh'))

In [3]:
s.value_counts()[2:].replace([s.value_counts()[2:]], 'erre')

c    erre
e    erre
d    erre
h    erre
f    erre
g    erre
dtype: object

In [13]:
s.value_counts()

a    8
b    7
c    6
e    5
d    4
h    3
f    2
g    1
dtype: int64

In [40]:
s.value_counts()[2:].index

Index(['c', 'e', 'd', 'h', 'f', 'g'], dtype='object')

In [15]:
s[s.isin(s.value_counts()[2:].index)]

2     d
3     c
5     d
6     h
8     f
9     c
10    e
11    e
14    c
16    h
18    c
20    e
21    d
23    d
25    e
26    c
30    e
31    c
33    f
34    g
35    h
dtype: object

In [59]:
list(s.value_counts()[2:].index)

['c', 'e', 'd', 'h', 'f', 'g']

In [18]:
s.replace(['c', 'e', 'd', 'h', 'f', 'g'], 'Yet another value')

0                     a
1                     b
2     Yet another value
3     Yet another value
4                     b
5     Yet another value
6     Yet another value
7                     a
8     Yet another value
9     Yet another value
10    Yet another value
11    Yet another value
12                    a
13                    b
14    Yet another value
15                    a
16    Yet another value
17                    b
18    Yet another value
19                    a
20    Yet another value
21    Yet another value
22                    a
23    Yet another value
24                    a
25    Yet another value
26    Yet another value
27                    b
28                    b
29                    b
30    Yet another value
31    Yet another value
32                    a
33    Yet another value
34    Yet another value
35    Yet another value
dtype: object

# Задача №5

In [50]:
# Разбейте все значения из pandas.Series (переменная s1) на 3 интервала равного размера. Функция должна вернуть серию.

s1 = pd.Series(reversed(range(0, 10)))

In [51]:
s1

0    9
1    8
2    7
3    6
4    5
5    4
6    3
7    2
8    1
9    0
dtype: int64

In [52]:
pd.Series(pd.qcut(s1,3))

0       (6.0, 9.0]
1       (6.0, 9.0]
2       (6.0, 9.0]
3       (3.0, 6.0]
4       (3.0, 6.0]
5       (3.0, 6.0]
6    (-0.001, 3.0]
7    (-0.001, 3.0]
8    (-0.001, 3.0]
9    (-0.001, 3.0]
dtype: category
Categories (3, interval[float64, right]): [(-0.001, 3.0] < (3.0, 6.0] < (6.0, 9.0]]

# Задача №6

In [59]:
# Преобразуйте pandas.Series (переменная s1) в pandas.DataFrame размером 2 х 5.

s1 = pd.Series(range(0, 10))

In [60]:
s1

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [61]:
s1 = s1.values.reshape(2,5)
s1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]], dtype=int64)

In [62]:
pd.DataFrame(s1)

0  1  2  3  4
0  0  1  2  3  4
1  5  6  7  8  9

In [ ]:
# 27.05.2023

# Задача №7

In [63]:
# Найдите индексы значений, которые кратны 2.

s1 = pd.Series([5, 10, 2, 3, 9, 12, 1])

In [64]:
# не сходится с ответом т.к. каждое значение должно быть в []
np.array(s1[s1%2 == 0].index)

array([1, 2, 5], dtype=int64)

In [42]:
# так выдает с нулевым индексом, видимо потому что объект pd.Series
np.argwhere([s1%2 == 0])

array([[0, 1],
       [0, 2],
       [0, 5]], dtype=int64)

In [19]:
# в итоге надо: обернуть в np.array и уже потом искать по условию:

np.argwhere(np.array(s1) % 2 == 0)

array([[1],
       [2],
       [5]], dtype=int64)

# Задача №8

In [50]:
# Создайте новый pandas.Series из элементов, которые находятся по индексам: 0, 7, 12, 15, 19.
# Функция solution должна вернуть серию.

s1 = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))

In [58]:
df = pd.DataFrame(s1)

In [63]:
s1.take([0, 7, 12, 15, 19])

0     a
7     h
12    m
15    p
19    t
dtype: object

In [71]:
s1.take([3])

3    d
dtype: object

# Задача №9

In [72]:
# Преобразуйте элементы pandas.Series (переменная s1) из строк в даты. Функция solution должна вернуть серию.

s1 = pd.Series(['01 Jan 2022', '02-02-2022', '20220303', '2022/04/04', '2022-05-05', '2022-06-06T12:20'])

pandas.to_datetime

In [73]:
s1

0         01 Jan 2022
1          02-02-2022
2            20220303
3          2022/04/04
4          2022-05-05
5    2022-06-06T12:20
dtype: object

In [75]:
pd.to_datetime(s1)

0   2022-01-01 00:00:00
1   2022-02-02 00:00:00
2   2022-03-03 00:00:00
3   2022-04-04 00:00:00
4   2022-05-05 00:00:00
5   2022-06-06 12:20:00
dtype: datetime64[ns]

# Задача №10

In [65]:
# Объект pandas.Series (переменная s1) содержит некоторые числовые значения. 
# Для значений хранящихся в s2 определите индексы под которыми они хранятся  
# в s1. Функция должна вернуть список (python list):
    
# [5, 4, 0, 8]

s1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
s2 = pd.Series([1, 3, 10, 13])

In [66]:
s1

0    10
1     9
2     6
3     5
4     3
5     1
6    12
7     8
8    13
dtype: int64

In [67]:
s2

0     1
1     3
2    10
3    13
dtype: int64

In [68]:
s2.values

array([ 1,  3, 10, 13], dtype=int64)

In [6]:
lst = []
for i in s2:
    lst += (s1[s1 == i].index.to_list())

In [7]:
lst

[5, 4, 0, 8]

In [8]:
# Внимание правильный ответ:

list(pd.Index(s1).get_indexer(s2))

[5, 4, 0, 8]

In [9]:
# get_indexer работает с pd.Index

pd.Index(s1)

Int64Index([10, 9, 6, 5, 3, 1, 12, 8, 13], dtype='int64')

In [14]:
# передавать в get_indexer надо коллекцию например так [10]

pd.Index(s2).get_indexer([10])

array([2], dtype=int64)

In [ ]:
28.05.2023

# Задача № 11

In [4]:
# Даны следующие ряды данных:

# s_forecast - ряд прогнозных значений

# s_real - ряд фактических значений
 

# Вычислите среднеквадратичную ошибку.


s_forecast = pd.Series(range(10))
s_real  = pd.Series(reversed(range(10)))


In [10]:
s1 = s_forecast
s1

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [11]:
s2 = s_real
s2

0    9
1    8
2    7
3    6
4    5
5    4
6    3
7    2
8    1
9    0
dtype: int64

In [ ]:
# Среднеквадратичная ошибка (Mean Squared Error) – Среднее арифметическое (Mean) 
# квадратов разностей между предсказанными и реальными значениями Модели (Model) 
# Машинного обучения (ML):

# MSE позволяет оценить, насколько хорошо модель приближает истинные значения. 
# Чем меньше значение MSE, тем ближе предсказания модели к истинным значениям.

In [14]:
((s1 - s2)**2).mean()

33.0

# Задача № 12

In [50]:
# Измените первый символ каждого слова на верхний регистр.

s1 = pd.Series(['the', 'weather', 'is', 'fine']) 

In [23]:
s1[0][0]

't'

In [37]:
# с циклом:
for i in range(len(s1)):
    s1[i] = np.char.replace(s1[i], s1[i][0], s1[i][0].upper())

In [38]:
s1

0        The
1    Weather
2         Is
3       Fine
dtype: object

In [ ]:
# без цикла

In [53]:
s1.str.capitalize()

0        The
1    Weather
2         Is
3       Fine
dtype: object

# Задача №13

In [66]:
# Подсчитайте количество символов в каждом слове. Функция solution должна вернуть серию.

s1 = pd.Series(['the', 'weather', 'is', 'fine'])

In [77]:
result = pd.Series(s1.str.len())
result

0    3
1    7
2    2
3    4
dtype: int64

In [ ]:
20.06.2023

# Задача №14

In [ ]:
# Вытяните день месяца, номер недели, день года и день недели из серии (s1)

# Date:  [5, 4, 3, 4, 5, 6]
# Week number:  [1, 5, 13, 22, 9, 9]
# Day number of year:  [5, 35, 93, 155, 64, 65]
# Day of week:  ['Tuesday', 'Thursday', 'Saturday', 'Friday', 'Friday', 'Saturday']

In [69]:
s1 = pd.Series(['05 Jan 2021', '02-04-2021', '20210403', '2021/06/04', '2021-03-05', '2021-03-06T12:20'])

In [91]:
print('Date: ', list(pd.to_datetime(s1).dt.day))

print('Week number: ', list(pd.to_datetime(s1).dt.isocalendar().week))

print('Day number of year: ', list(pd.to_datetime(s1).dt.dayofyear))

print('Day of week: ', list(pd.to_datetime(s1).dt.day_name()))

Date:  [5, 4, 3, 4, 5, 6]
Week number:  [1, 5, 13, 22, 9, 9]
Day number of year:  [5, 35, 93, 155, 64, 65]
Day of week:  ['Tuesday', 'Thursday', 'Saturday', 'Friday', 'Friday', 'Saturday']


# Задача №15

In [ ]:
# Измените даты лежащие в серии (s1) таким образом чтобы они начинались с 10-го числа соответствующего месяца.

# Требуемый финальный результат (наполнение):
# 0   2022-01-10
# 1   2022-02-10
# 2   2022-03-10
# dtype: datetime64[ns]

In [110]:
s1 = pd.Series(['Jan 2022', 'Feb 2022', 'Mar 2022'])

In [93]:
s1

0    Jan 2022
1    Feb 2022
2    Mar 2022
dtype: object

In [96]:
pd.to_datetime(s1)

0   2022-01-01
1   2022-02-01
2   2022-03-01
dtype: datetime64[ns]

In [101]:
pd.to_datetime(s1).dt.year

0    2022
1    2022
2    2022
dtype: int64

In [102]:
pd.to_datetime(s1).dt.month

0    1
1    2
2    3
dtype: int64

In [114]:
df = pd.DataFrame({'year': list(pd.to_datetime(s1).dt.year),
                   'month': list(pd.to_datetime(s1).dt.month),
                   'day': [10 for i in range (len(s1))]})

In [115]:
df

year  month  day
0  2022      1   10
1  2022      2   10
2  2022      3   10

In [117]:
pd.to_datetime(df)

0   2022-01-10
1   2022-02-10
2   2022-03-10
dtype: datetime64[ns]

### Несколько вариантов решения этой задачи из комментариев:

### Вариант №1

In [120]:
# Шаг 1. Преобразуем изначальную серию old_series в серию с датами new_series:
new_series = pd.to_datetime(s1)

In [121]:
new_series

0   2022-01-01
1   2022-02-01
2   2022-03-01
dtype: datetime64[ns]

In [122]:
# Шаг 2. Создадим значение количества дней, на которое нужно изменить new_serias:
days_amount = pd.Timedelta(days=9)

In [125]:
days_amount

Timedelta('9 days 00:00:00')

In [123]:
# Шаг 3. Преобразуем new_series в финальную с нужной датой final_series:
final_series = new_series + days_amount

In [126]:
final_series

0   2022-01-10
1   2022-02-10
2   2022-03-10
dtype: datetime64[ns]

### Вариант№2

In [127]:
s1

0    Jan 2022
1    Feb 2022
2    Mar 2022
dtype: object

In [138]:
s11 = pd.to_datetime(s1)

In [152]:
s11

0   2022-01-01
1   2022-02-01
2   2022-03-01
dtype: datetime64[ns]

In [154]:
s11.apply(lambda x: x.replace(day=10))

0   2022-01-10
1   2022-02-10
2   2022-03-10
dtype: datetime64[ns]

In [157]:
s11[0].replace(day=10)

Timestamp('2022-01-10 00:00:00')

In [ ]:
26.06.2023

# Задача №16

In [138]:
# Из серии (s1) вытяните слова, содержащие не менее 2 гласных.

# Сложность: 💪💪💪 
    
s1 = pd.Series(['Apple', 'Orange', 'Plan', 'Sky', 'Money'])

In [69]:
vow = ['a', 'e', 'i', 'o', 'u']

In [37]:
s1.apply(lambda x: x in vow)

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [136]:
lst = []
lst_index = []
def calc_vows(x):    
    cnt = 0
    for i in vow:
        if i in x.lower():
            cnt +=1
            if cnt >= 2:
                lst.append(x)
                lst_index.append()
                break
    return lst

In [133]:
lst

['Apple', 'Orange', 'Money']

In [135]:
lst_index

[<function str.index>, <function str.index>, <function str.index>]

In [121]:
pd.Series(lst)

0     Apple
1    Orange
2     Money
dtype: object

In [150]:
import pandas as pd
import numpy as np

lst = []
vow = ['a', 'e', 'i', 'o', 'u']
def calc_vows(x):    
    cnt = 0
    for i in vow:
        if i in x.lower():
            cnt +=1
            if cnt >= 2:
                lst.append(x)
                break
    return lst


def solution():
    s1 = pd.Series(['Apple', 'Orange', 'Plan', 'Sky', 'Money'])
    
    s1.apply(lambda x: calc_vows(x))
    result = pd.Series(list(lst), index = [pd.Index(s1).get_indexer(lst)])
    return result

In [151]:
solution()

0     Apple
1    Orange
4     Money
dtype: object

In [2]:
# Внимание правильное решение:

import pandas as pd
import numpy as np

s1 = pd.Series(['Apple', 'Orange', 'Plan', 'Sky', 'Money'])
s2 = s1.str.count('[aeiouyAEIOUY]')

print(s1[s2 >= 2])

0     Apple
1    Orange
4     Money
dtype: object


In [162]:
s1.str.count('[aeiouyAEIOUY]')

0    2
1    3
2    1
3    1
4    3
dtype: int64

In [ ]:
27.06.2023

# Задача №17

In [ ]:
# Сложность: 💪💪💪 

# Извлеките корректные почтовые адреса из серии (s1). Используйте pattern для этой задачи.

# Требуемый финальный результат (наполнение):
# 1          help@stepik.com
# 2                user@t.co
# 3    lovepandas@google.com
# dtype: object

In [14]:
# import pandas as pd
# import numpy as np

# def solution():
#     s1 = pd.Series(['teach pandas at stepik.com', 'help@stepik.com', 'user@t.co', 'lovepandas@google.com'])
#     pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
#     result = # ваш код здесь)
#     return result

In [16]:
s1 = pd.Series(['teach pandas at stepik.com', 'help@stepik.com', 'user@t.co', 'lovepandas@google.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

In [44]:
# И снова рубрика "небольшие подсказки".
# Шаг 1. Воспользуемся супер функций pandas.Series.str.findall (спасибо Роману Медведеву за подсказку),
# эта функция принимает в себя аргумент в виде паттерна (или регулярное выражение), а возвращает все
# совпадения с этим паттерном каждой строки серии. Т.е. если не будет совпадения, 
# то функция вернут пустой список.

s = s1.str.findall(pattern)
s

0                         []
1          [help@stepik.com]
2                [user@t.co]
3    [lovepandas@google.com]
dtype: object

In [50]:
ss = s[s.str.len() != 0]
ss

1          [help@stepik.com]
2                [user@t.co]
3    [lovepandas@google.com]
dtype: object

In [52]:
# Избавимся от квадратных скобок. Нам поможет функция pandas.Series.explode,
# которая ничего не принимает в виде аргумента, а возвращает dtype строк 
# подмножества в виде object. Нам это и нужно.
# код:
# s4 = s3.explode()

In [53]:
ss.explode()

1          help@stepik.com
2                user@t.co
3    lovepandas@google.com
dtype: object

In [49]:
result = ss.apply(lambda x: x[0])
result

1          help@stepik.com
2                user@t.co
3    lovepandas@google.com
dtype: object

In [51]:
s[s.str.len() != 0].apply(lambda x: x[0])

1          help@stepik.com
2                user@t.co
3    lovepandas@google.com
dtype: object