In [1]:
import numpy as np
import pandas as pd

In [ ]:
# ЗАДАЧА № 0
# Получите элементы s1, которые не присутствуют в s2. Функция должна вернуть серию.

In [39]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([4, 5, 6, 7, 8])

In [42]:
s1[~s1.isin(s2)]

0    1
1    2
2    3
dtype: int64

In [91]:
s1[~np.isin(s1, s2)]

0    1
1    2
2    3
dtype: int64

In [ ]:
# ЗАДАЧА №1

# Создайте новый pandas.Series из элементов, которые присутствуют только в 
# одном из двух pandas.Series (переменные s1, s2). 

# Если элемент присутствует в двух Series, то включать его не надо.

In [32]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([4, 5, 6, 7, 8])

In [33]:
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [34]:
s2

0    4
1    5
2    6
3    7
4    8
dtype: int64

In [49]:
s3 = np.union1d(s1,s2)
s3

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [50]:
s4 = np.intersect1d(s1,s2)
s4

array([4, 5], dtype=int64)

In [55]:
# серия из п.1[~серия из п.1isin(серия из п.2)])

In [61]:
# можно так:
s3[~np.isin(s3, s4)]

array([1, 2, 3, 6, 7, 8], dtype=int64)

In [92]:
# можно так:
s3[~s3.isin(s4)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [95]:
# можно так:
s3[~np.isin(s3, np.intersect1d(s1,s2))]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [126]:
# чтобы Stepik принял задание нужно так:

s3 = pd.Series(np.union1d(s1,s2))
s3

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [127]:
s4 = pd.Series(np.intersect1d(s1,s2))
s4

0    4
1    5
dtype: int64

In [130]:
s3[~s3.isin(s4)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [135]:
s3[~np.isin(s3,s4)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64