In [3]:
import numpy as np
import pandas as pd

# ЗАДАЧА № 0

In [3]:

# Получите элементы s1, которые не присутствуют в s2. Функция должна вернуть серию.

In [4]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([4, 5, 6, 7, 8])

In [8]:
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [9]:
s2

0    4
1    5
2    6
3    7
4    8
dtype: int64

In [10]:
s1[s1.isin(s2)]

3    4
4    5
dtype: int64

In [5]:
s1[~s1.isin(s2)]

0    1
1    2
2    3
dtype: int64

In [6]:
s1[~np.isin(s1, s2)]

0    1
1    2
2    3
dtype: int64

In [7]:
s1[~np.isin(s2, s1)]

2    3
3    4
4    5
dtype: int64

# ЗАДАЧА №1

In [ ]:
# Создайте новый pandas.Series из элементов, которые присутствуют только в 
# одном из двух pandas.Series (переменные s1, s2). 

# Если элемент присутствует в двух Series, то включать его не надо.

In [11]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([4, 5, 6, 7, 8])

In [12]:
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [13]:
s2

0    4
1    5
2    6
3    7
4    8
dtype: int64

In [14]:
s3 = np.union1d(s1,s2)
s3

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [15]:
s4 = np.intersect1d(s1,s2)
s4

array([4, 5], dtype=int64)

In [61]:
# можно так:
s3[~np.isin(s3, s4)]

array([1, 2, 3, 6, 7, 8], dtype=int64)

In [92]:
# можно так:
s3[~s3.isin(s4)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [95]:
# можно так:
s3[~np.isin(s3, np.intersect1d(s1,s2))]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [126]:
# чтобы Stepik принял задание нужно так:

s3 = pd.Series(np.union1d(s1,s2))
s3

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [127]:
s4 = pd.Series(np.intersect1d(s1,s2))
s4

0    4
1    5
dtype: int64

In [130]:
s3[~s3.isin(s4)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [135]:
s3[~np.isin(s3,s4)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

# Задача №2

In [ ]:
# На вход подается pd.Series

# Найти:

# наименьшее значение
# 25 перцентиль
# медиану
# 75 перцентиль
# наибольшее значение
# Все значения должны быть упакованы в серию.

In [17]:
ser = pd.Series([12.539048, 5.688863, 16.247349, 9.601944, 5.551343, 5.591008, 10.093195, 11.189223, 10.067743, 1.822353])

In [18]:
ser

0    12.539048
1     5.688863
2    16.247349
3     9.601944
4     5.551343
5     5.591008
6    10.093195
7    11.189223
8    10.067743
9     1.822353
dtype: float64

In [21]:
minima = np.min(ser)
minima

1.822353

In [24]:
percentile_25 = np.percentile(ser, 25)
percentile_25

5.61547175

In [27]:
mediana = np.median(ser)
mediana

9.8348435

In [28]:
percentile_75 = np.percentile(ser, 75)
percentile_75

10.915216000000001

In [29]:
maxi = np.max(ser)
maxi

16.247349

In [32]:
result = pd.Series([minima, percentile_25, mediana, percentile_75, maxi])
result

0     1.822353
1     5.615472
2     9.834843
3    10.915216
4    16.247349
dtype: float64

In [33]:
# Процентиль - это некая граница, которая делит всю выборку данных на определенные части 
# соглано их частоте повторений. Другими словами, если у нас 100 студентов сдали экзамен 
# с некоторым результатом (5 студентов на отлично, 45 студентов на хорошо, 15 студентов 
# на удовлетворительно, а остальные - на неудовлетворительно), 
# то интерпретация будет такой: 5% студентов сдали на отлично (5% процентиль, т.е. все 
# отличники попали в группу, которая занимает не более 5% от всей выборки. 
# По остальным студентоам аналогично).
# Поэтому, например, 25-я процентиль отсекает данные от общей выборки так, что в
# ней остаются только те данные, что имеют частоту появления ниже 25%. Аналогично 
# и с 75-ой процентилью, которая делит выборку так, что остаются только те данные, 
# что встречаются не более 75%. С медианой (50%) всё аналогично.
# А вот с минимум и максимум могу добавить только то, что наименьшему значению 
# соответствует нулевой процентиль, наибольшему - 100-й процентиль, как в аналогии, 
# что медиане соответствует 50-й процентиль и т.д.

# https://www.youtube.com/watch?v=SaF2G5WMwt   


# Поэтому правильный и локоничный код будет следующим:

np.percentile(ser, [0, 25, 50, 75, 100])

array([ 1.822353  ,  5.61547175,  9.8348435 , 10.915216  , 16.247349  ])

# Задача №3

In [ ]:
# Определите сколько раз встречается каждое значение в исходном pandas.Series (переменная s). 
# Функция должна вернуть серию с подсчитанным количеством каждого символа.

In [34]:
s = pd.Series(list('abdcbdhafceeabcahbcaedadaecbbbecafgh'))

In [35]:
s.value_counts()

a    8
b    7
c    6
e    5
d    4
h    3
f    2
g    1
dtype: int64

# Задача №4

In [2]:
# Доработайте код таким образом, чтобы оставить только 2 наиболее встречающихся значения, а для остальных установите 
# значение 'Yet another value'.

# Функция solution должна возвращать серию.

# Финальный результат, который должен получиться:
# 0                     a
# 1                     b
# 2     Yet another value
# 3     Yet another value
# 4                     b
# .........................

s = pd.Series(list('abdcbdhafceeabcahbcaedadaecbbbecafgh'))

In [26]:
s.value_counts()[2:].replace([s.value_counts()[2:]], 'erre')

c    erre
e    erre
d    erre
h    erre
f    erre
g    erre
dtype: object

In [40]:
s.value_counts()[2:].index

Index(['c', 'e', 'd', 'h', 'f', 'g'], dtype='object')

In [50]:
s[s.isin(s.value_counts()[2:].index)]

2     d
3     c
5     d
6     h
8     f
9     c
10    e
11    e
14    c
16    h
18    c
20    e
21    d
23    d
25    e
26    c
30    e
31    c
33    f
34    g
35    h
dtype: object

In [59]:
list(s.value_counts()[2:].index)

['c', 'e', 'd', 'h', 'f', 'g']

In [56]:
s

0     a
1     b
2     d
3     c
4     b
5     d
6     h
7     a
8     f
9     c
10    e
11    e
12    a
13    b
14    c
15    a
16    h
17    b
18    c
19    a
20    e
21    d
22    a
23    d
24    a
25    e
26    c
27    b
28    b
29    b
30    e
31    c
32    a
33    f
34    g
35    h
dtype: object

In [61]:
s.replace(list(s.value_counts()[2:].index), 'Yet another value')

0                     a
1                     b
2     Yet another value
3     Yet another value
4                     b
5     Yet another value
6     Yet another value
7                     a
8     Yet another value
9     Yet another value
10    Yet another value
11    Yet another value
12                    a
13                    b
14    Yet another value
15                    a
16    Yet another value
17                    b
18    Yet another value
19                    a
20    Yet another value
21    Yet another value
22                    a
23    Yet another value
24                    a
25    Yet another value
26    Yet another value
27                    b
28                    b
29                    b
30    Yet another value
31    Yet another value
32                    a
33    Yet another value
34    Yet another value
35    Yet another value
dtype: object

# Задача №5

In [62]:
# Разбейте все значения из pandas.Series (переменная s1) на 3 интервала равного размера. Функция должна вернуть серию.

s1 = pd.Series(reversed(range(0, 10)))

In [64]:
s1

0    9
1    8
2    7
3    6
4    5
5    4
6    3
7    2
8    1
9    0
dtype: int64

In [66]:
pd.Series(pd.qcut(s1,3))

0       (6.0, 9.0]
1       (6.0, 9.0]
2       (6.0, 9.0]
3       (3.0, 6.0]
4       (3.0, 6.0]
5       (3.0, 6.0]
6    (-0.001, 3.0]
7    (-0.001, 3.0]
8    (-0.001, 3.0]
9    (-0.001, 3.0]
dtype: category
Categories (3, interval[float64, right]): [(-0.001, 3.0] < (3.0, 6.0] < (6.0, 9.0]]

# Задача №6

In [79]:
# Преобразуйте pandas.Series (переменная s1) в pandas.DataFrame размером 2 х 5.

s1 = pd.Series(range(0, 10))

In [80]:
s1 = s1.values.reshape(2,5)

In [81]:
pd.DataFrame(s1)

0  1  2  3  4
0  0  1  2  3  4
1  5  6  7  8  9

In [ ]:
# 27.05.2023

# Задача №7

In [15]:
# Найдите индексы значений, которые кратны 2.

s1 = pd.Series([5, 10, 2, 3, 9, 12, 1])

In [18]:
# не сходится с ответом т.к. каждое значение должно быть в []
np.array(s1[s1%2 == 0].index)

array([1, 2, 5], dtype=int64)

In [42]:
# так выдает с нулевым индексом, видимо потому что объект pd.Series
np.argwhere([s1%2 == 0])

array([[0, 1],
       [0, 2],
       [0, 5]], dtype=int64)

In [19]:
# в итоге надо: обернуть в np.array и уже потом искать по условию:

np.argwhere(np.array(s1) % 2 == 0)

array([[1],
       [2],
       [5]], dtype=int64)

# Задача №8

In [50]:
# Создайте новый pandas.Series из элементов, которые находятся по индексам: 0, 7, 12, 15, 19.
# Функция solution должна вернуть серию.

s1 = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))

In [58]:
df = pd.DataFrame(s1)

In [63]:
s1.take([0, 7, 12, 15, 19])

0     a
7     h
12    m
15    p
19    t
dtype: object

In [71]:
s1.take([3])

3    d
dtype: object

# Задача №9

In [72]:
# Преобразуйте элементы pandas.Series (переменная s1) из строк в даты. Функция solutionдолжна вернуть серию.

s1 = pd.Series(['01 Jan 2022', '02-02-2022', '20220303', '2022/04/04', '2022-05-05', '2022-06-06T12:20'])

pandas.to_datetime

In [73]:
s1

0         01 Jan 2022
1          02-02-2022
2            20220303
3          2022/04/04
4          2022-05-05
5    2022-06-06T12:20
dtype: object

In [75]:
pd.to_datetime(s1)

0   2022-01-01 00:00:00
1   2022-02-02 00:00:00
2   2022-03-03 00:00:00
3   2022-04-04 00:00:00
4   2022-05-05 00:00:00
5   2022-06-06 12:20:00
dtype: datetime64[ns]

# Задача №10

In [3]:
# Объект pandas.Series (переменная s1) содержит некоторые числовые значения. 
# Для значений хранящихся в s2 определите индексы под которыми они хранятся  
# в s1. Функция должна вернуть список (python list):
    
# [5, 4, 0, 8]

s1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
s2 = pd.Series([1, 3, 10, 13])

In [89]:
s1

0    10
1     9
2     6
3     5
4     3
5     1
6    12
7     8
8    13
dtype: int64

In [90]:
s2

0     1
1     3
2    10
3    13
dtype: int64

In [91]:
s2.values

array([ 1,  3, 10, 13], dtype=int64)

In [6]:
lst = []
for i in s2:
    lst += (s1[s1 == i].index.to_list())

In [7]:
lst

[5, 4, 0, 8]

In [8]:
# Внимание правильный ответ:

list(pd.Index(s1).get_indexer(s2))

[5, 4, 0, 8]

In [9]:
# get_indexer работает с pd.Index

pd.Index(s1)

Int64Index([10, 9, 6, 5, 3, 1, 12, 8, 13], dtype='int64')

In [14]:
# передавать в get_indexer надо коллекцию например так [10]

pd.Index(s2).get_indexer([10])

array([2], dtype=int64)

In [ ]:
28.05.2023

# Задача № 11

In [4]:
# Даны следующие ряды данных:

# s_forecast - ряд прогнозных значений

# s_real - ряд фактических значений
 

# Вычислите среднеквадратичную ошибку.


s_forecast = pd.Series(range(10))
s_real  = pd.Series(reversed(range(10)))


In [10]:
s1 = s_forecast
s1

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [11]:
s2 = s_real
s2

0    9
1    8
2    7
3    6
4    5
5    4
6    3
7    2
8    1
9    0
dtype: int64

In [ ]:
# Среднеквадратичная ошибка (Mean Squared Error) – Среднее арифметическое (Mean) 
# квадратов разностей между предсказанными и реальными значениями Модели (Model) 
# Машинного обучения (ML):

# MSE позволяет оценить, насколько хорошо модель приближает истинные значения. 
# Чем меньше значение MSE, тем ближе предсказания модели к истинным значениям.

In [14]:
((s1 - s2)**2).mean()

33.0

# Задача № 12

In [50]:
# Измените первый символ каждого слова на верхний регистр.

s1 = pd.Series(['the', 'weather', 'is', 'fine']) 

In [23]:
s1[0][0]

't'

In [37]:
# с циклом:
for i in range(len(s1)):
    s1[i] = np.char.replace(s1[i], s1[i][0], s1[i][0].upper())

In [38]:
s1

0        The
1    Weather
2         Is
3       Fine
dtype: object

In [ ]:
# без цикла

In [53]:
s1.str.capitalize()

0        The
1    Weather
2         Is
3       Fine
dtype: object

# Задача №13

In [66]:
# Подсчитайте количество символов в каждом слове. Функция solution должна вернуть серию.

s1 = pd.Series(['the', 'weather', 'is', 'fine'])

In [77]:
result = pd.Series(s1.str.len())
result

0    3
1    7
2    2
3    4
dtype: int64