In [2]:
import numpy as np
import pandas as pd

# ЗАДАЧА № 0

In [3]:

# Получите элементы s1, которые не присутствуют в s2. Функция должна вернуть серию.

In [4]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([4, 5, 6, 7, 8])

In [8]:
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [9]:
s2

0    4
1    5
2    6
3    7
4    8
dtype: int64

In [10]:
s1[s1.isin(s2)]

3    4
4    5
dtype: int64

In [5]:
s1[~s1.isin(s2)]

0    1
1    2
2    3
dtype: int64

In [6]:
s1[~np.isin(s1, s2)]

0    1
1    2
2    3
dtype: int64

In [7]:
s1[~np.isin(s2, s1)]

2    3
3    4
4    5
dtype: int64

# ЗАДАЧА №1

In [ ]:


# Создайте новый pandas.Series из элементов, которые присутствуют только в 
# одном из двух pandas.Series (переменные s1, s2). 

# Если элемент присутствует в двух Series, то включать его не надо.

In [11]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([4, 5, 6, 7, 8])

In [12]:
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [13]:
s2

0    4
1    5
2    6
3    7
4    8
dtype: int64

In [14]:
s3 = np.union1d(s1,s2)
s3

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [15]:
s4 = np.intersect1d(s1,s2)
s4

array([4, 5], dtype=int64)

In [55]:
# серия из п.1[~серия из п.1isin(серия из п.2)])

In [61]:
# можно так:
s3[~np.isin(s3, s4)]

array([1, 2, 3, 6, 7, 8], dtype=int64)

In [92]:
# можно так:
s3[~s3.isin(s4)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [95]:
# можно так:
s3[~np.isin(s3, np.intersect1d(s1,s2))]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [126]:
# чтобы Stepik принял задание нужно так:

s3 = pd.Series(np.union1d(s1,s2))
s3

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [127]:
s4 = pd.Series(np.intersect1d(s1,s2))
s4

0    4
1    5
dtype: int64

In [130]:
s3[~s3.isin(s4)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [135]:
s3[~np.isin(s3,s4)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

# Задача №2

In [ ]:


# На вход подается pd.Series

# Найти:

# наименьшее значение
# 25 перцентиль
# медиану
# 75 перцентиль
# наибольшее значение
# Все значения должны быть упакованы в серию.

In [17]:
ser = pd.Series([12.539048, 5.688863, 16.247349, 9.601944, 5.551343, 5.591008, 10.093195, 11.189223, 10.067743, 1.822353])

In [18]:
ser

0    12.539048
1     5.688863
2    16.247349
3     9.601944
4     5.551343
5     5.591008
6    10.093195
7    11.189223
8    10.067743
9     1.822353
dtype: float64

In [21]:
minima = np.min(ser)
minima

1.822353

In [24]:
percentile_25 = np.percentile(ser, 25)
percentile_25

5.61547175

In [27]:
mediana = np.median(ser)
mediana

9.8348435

In [28]:
percentile_75 = np.percentile(ser, 75)
percentile_75

10.915216000000001

In [29]:
maxi = np.max(ser)
maxi

16.247349

In [32]:
result = pd.Series([minima, percentile_25, mediana, percentile_75, maxi])
result

0     1.822353
1     5.615472
2     9.834843
3    10.915216
4    16.247349
dtype: float64

In [33]:
# Процентиль - это некая граница, которая делит всю выборку данных на определенные части 
# соглано их частоте повторений. Другими словами, если у нас 100 студентов сдали экзамен 
# с некоторым результатом (5 студентов на отлично, 45 студентов на хорошо, 15 студентов 
# на удовлетворительно, а остальные - на неудовлетворительно), 
# то интерпретация будет такой: 5% студентов сдали на отлично (5% процентиль, т.е. все 
# отличники попали в группу, которая занимает не более 5% от всей выборки. 
# По остальным студентоам аналогично).
# Поэтому, например, 25-я процентиль отсекает данные от общей выборки так, что в
# ней остаются только те данные, что имеют частоту появления ниже 25%. Аналогично 
# и с 75-ой процентилью, которая делит выборку так, что остаются только те данные, 
# что встречаются не более 75%. С медианой (50%) всё аналогично.
# А вот с минимум и максимум могу добавить только то, что наименьшему значению 
# соответствует нулевой процентиль, наибольшему - 100-й процентиль, как в аналогии, 
# что медиане соответствует 50-й процентиль и т.д.

https://www.youtube.com/watch?v=SaF2G5WMwtg
    


# Поэтому правильный и локоничный код будет следующим:

np.percentile(ser, [0, 25, 50, 75, 100])

array([ 1.822353  ,  5.61547175,  9.8348435 , 10.915216  , 16.247349  ])

# Задача №3

In [ ]:

# Определите сколько раз встречается каждое значение в исходном pandas.Series (переменная s). 
# Функция должна вернуть серию с подсчитанным количеством каждого символа.

In [34]:
s = pd.Series(list('abdcbdhafceeabcahbcaedadaecbbbecafgh'))

In [35]:
s.value_counts()

a    8
b    7
c    6
e    5
d    4
h    3
f    2
g    1
dtype: int64