In [1]:
import numpy as np
import pandas as pd

# ЗАДАЧА № 0

In [3]:
# Получите элементы s1, которые не присутствуют в s2. Функция должна вернуть серию.

In [2]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([4, 5, 6, 7, 8])

In [3]:
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
s2

0    4
1    5
2    6
3    7
4    8
dtype: int64

In [5]:
s1[s1.isin(s2)]

3    4
4    5
dtype: int64

In [6]:
s1[~s1.isin(s2)]

0    1
1    2
2    3
dtype: int64

In [7]:
s1[~np.isin(s1, s2)]

0    1
1    2
2    3
dtype: int64

In [8]:
s1[~np.isin(s2, s1)]

2    3
3    4
4    5
dtype: int64

In [10]:
np.isin(s1, s2)

array([False, False, False,  True,  True])

In [11]:
np.isin(s2, s1)

array([ True,  True, False, False, False])

# ЗАДАЧА №1

In [ ]:
# Создайте новый pandas.Series из элементов, которые присутствуют только в 
# одном из двух pandas.Series (переменные s1, s2).

# Если элемент присутствует в двух Series, то включать его не надо.

In [12]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([4, 5, 6, 7, 8])

In [13]:
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [14]:
s2

0    4
1    5
2    6
3    7
4    8
dtype: int64

In [17]:
s3 = np.union1d(s1,s2)
s3

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [18]:
s4 = np.intersect1d(s1,s2)
s4

array([4, 5], dtype=int64)

In [61]:
# можно так:
s3[~np.isin(s3, s4)]

array([1, 2, 3, 6, 7, 8], dtype=int64)

In [19]:
np.isin(s3, s4)

array([False, False, False,  True,  True, False, False, False])

In [92]:
# можно так:
s3[~s3.isin(s4)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [95]:
# можно так:
s3[~np.isin(s3, np.intersect1d(s1,s2))]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [126]:
# чтобы Stepik принял задание нужно так:

s3 = pd.Series(np.union1d(s1,s2))
s3

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [127]:
s4 = pd.Series(np.intersect1d(s1,s2))
s4

0    4
1    5
dtype: int64

In [130]:
s3[~s3.isin(s4)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [135]:
s3[~np.isin(s3,s4)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

# Задача №2

In [ ]:
# На вход подается pd.Series

# Найти:

# наименьшее значение
# 25 перцентиль
# медиану
# 75 перцентиль
# наибольшее значение
# Все значения должны быть упакованы в серию.

In [20]:
ser = pd.Series([12.539048, 5.688863, 16.247349, 9.601944, 5.551343, 5.591008, 10.093195, 11.189223, 10.067743, 1.822353])

In [21]:
ser

0    12.539048
1     5.688863
2    16.247349
3     9.601944
4     5.551343
5     5.591008
6    10.093195
7    11.189223
8    10.067743
9     1.822353
dtype: float64

In [27]:
minima = np.min(ser)
minima

1.822353

In [28]:
percentile_25 = np.percentile(ser, 25)
percentile_25

5.61547175

In [29]:
mediana = np.median(ser)
mediana

9.8348435

In [30]:
percentile_75 = np.percentile(ser, 75)
percentile_75

10.915216000000001

In [31]:
maxi = np.max(ser)
maxi

16.247349

In [32]:
result = pd.Series([minima, percentile_25, mediana, percentile_75, maxi])
result

0     1.822353
1     5.615472
2     9.834843
3    10.915216
4    16.247349
dtype: float64

In [33]:
# Процентиль - это некая граница, которая делит всю выборку данных на определенные части 
# соглано их частоте повторений. Другими словами, если у нас 100 студентов сдали экзамен 
# с некоторым результатом (5 студентов на отлично, 45 студентов на хорошо, 15 студентов 
# на удовлетворительно, а остальные - на неудовлетворительно), 
# то интерпретация будет такой: 5% студентов сдали на отлично (5% процентиль, т.е. все 
# отличники попали в группу, которая занимает не более 5% от всей выборки. 
# По остальным студентоам аналогично).
# Поэтому, например, 25-я процентиль отсекает данные от общей выборки так, что в
# ней остаются только те данные, что имеют частоту появления ниже 25%. Аналогично 
# и с 75-ой процентилью, которая делит выборку так, что остаются только те данные, 
# что встречаются не более 75%. С медианой (50%) всё аналогично.
# А вот с минимум и максимум могу добавить только то, что наименьшему значению 
# соответствует нулевой процентиль, наибольшему - 100-й процентиль, как в аналогии, 
# что медиане соответствует 50-й процентиль и т.д.

# https://www.youtube.com/watch?v=SaF2G5WMwt   


# Поэтому правильный и локоничный код будет следующим:

np.percentile(ser, [0, 25, 50, 75, 100])

array([ 1.822353  ,  5.61547175,  9.8348435 , 10.915216  , 16.247349  ])

# Задача №3

In [ ]:
# Определите сколько раз встречается каждое значение в исходном pandas.Series (переменная s). 
# Функция должна вернуть серию с подсчитанным количеством каждого символа.

In [33]:
s = pd.Series(list('abdcbdhafceeabcahbcaedadaecbbbecafgh'))

In [34]:
s.value_counts()

a    8
b    7
c    6
e    5
d    4
h    3
f    2
g    1
dtype: int64

# Задача №4

In [2]:
# Доработайте код таким образом, чтобы оставить только 2 наиболее встречающихся значения, а для остальных установите 
# значение 'Yet another value'.

# Функция solution должна возвращать серию.

# Финальный результат, который должен получиться:
# 0                     a
# 1                     b
# 2     Yet another value
# 3     Yet another value
# 4                     b
# .........................

s = pd.Series(list('abdcbdhafceeabcahbcaedadaecbbbecafgh'))

In [3]:
s.value_counts()[2:].replace([s.value_counts()[2:]], 'erre')

c    erre
e    erre
d    erre
h    erre
f    erre
g    erre
dtype: object

In [13]:
s.value_counts()

a    8
b    7
c    6
e    5
d    4
h    3
f    2
g    1
dtype: int64

In [40]:
s.value_counts()[2:].index

Index(['c', 'e', 'd', 'h', 'f', 'g'], dtype='object')

In [15]:
s[s.isin(s.value_counts()[2:].index)]

2     d
3     c
5     d
6     h
8     f
9     c
10    e
11    e
14    c
16    h
18    c
20    e
21    d
23    d
25    e
26    c
30    e
31    c
33    f
34    g
35    h
dtype: object

In [59]:
list(s.value_counts()[2:].index)

['c', 'e', 'd', 'h', 'f', 'g']

In [18]:
s.replace(['c', 'e', 'd', 'h', 'f', 'g'], 'Yet another value')

0                     a
1                     b
2     Yet another value
3     Yet another value
4                     b
5     Yet another value
6     Yet another value
7                     a
8     Yet another value
9     Yet another value
10    Yet another value
11    Yet another value
12                    a
13                    b
14    Yet another value
15                    a
16    Yet another value
17                    b
18    Yet another value
19                    a
20    Yet another value
21    Yet another value
22                    a
23    Yet another value
24                    a
25    Yet another value
26    Yet another value
27                    b
28                    b
29                    b
30    Yet another value
31    Yet another value
32                    a
33    Yet another value
34    Yet another value
35    Yet another value
dtype: object

# Задача №5

In [50]:
# Разбейте все значения из pandas.Series (переменная s1) на 3 интервала равного размера. Функция должна вернуть серию.

s1 = pd.Series(reversed(range(0, 10)))

In [51]:
s1

0    9
1    8
2    7
3    6
4    5
5    4
6    3
7    2
8    1
9    0
dtype: int64

In [52]:
pd.Series(pd.qcut(s1,3))

0       (6.0, 9.0]
1       (6.0, 9.0]
2       (6.0, 9.0]
3       (3.0, 6.0]
4       (3.0, 6.0]
5       (3.0, 6.0]
6    (-0.001, 3.0]
7    (-0.001, 3.0]
8    (-0.001, 3.0]
9    (-0.001, 3.0]
dtype: category
Categories (3, interval[float64, right]): [(-0.001, 3.0] < (3.0, 6.0] < (6.0, 9.0]]

# Задача №6

In [59]:
# Преобразуйте pandas.Series (переменная s1) в pandas.DataFrame размером 2 х 5.

s1 = pd.Series(range(0, 10))

In [60]:
s1

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [61]:
s1 = s1.values.reshape(2,5)
s1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]], dtype=int64)

In [62]:
pd.DataFrame(s1)

0  1  2  3  4
0  0  1  2  3  4
1  5  6  7  8  9

In [ ]:
# 27.05.2023

# Задача №7

In [63]:
# Найдите индексы значений, которые кратны 2.

s1 = pd.Series([5, 10, 2, 3, 9, 12, 1])

In [64]:
# не сходится с ответом т.к. каждое значение должно быть в []
np.array(s1[s1%2 == 0].index)

array([1, 2, 5], dtype=int64)

In [42]:
# так выдает с нулевым индексом, видимо потому что объект pd.Series
np.argwhere([s1%2 == 0])

array([[0, 1],
       [0, 2],
       [0, 5]], dtype=int64)

In [19]:
# в итоге надо: обернуть в np.array и уже потом искать по условию:

np.argwhere(np.array(s1) % 2 == 0)

array([[1],
       [2],
       [5]], dtype=int64)

# Задача №8

In [50]:
# Создайте новый pandas.Series из элементов, которые находятся по индексам: 0, 7, 12, 15, 19.
# Функция solution должна вернуть серию.

s1 = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))

In [58]:
df = pd.DataFrame(s1)

In [63]:
s1.take([0, 7, 12, 15, 19])

0     a
7     h
12    m
15    p
19    t
dtype: object

In [71]:
s1.take([3])

3    d
dtype: object

# Задача №9

In [72]:
# Преобразуйте элементы pandas.Series (переменная s1) из строк в даты. Функция solution должна вернуть серию.

s1 = pd.Series(['01 Jan 2022', '02-02-2022', '20220303', '2022/04/04', '2022-05-05', '2022-06-06T12:20'])

pandas.to_datetime

In [73]:
s1

0         01 Jan 2022
1          02-02-2022
2            20220303
3          2022/04/04
4          2022-05-05
5    2022-06-06T12:20
dtype: object

In [75]:
pd.to_datetime(s1)

0   2022-01-01 00:00:00
1   2022-02-02 00:00:00
2   2022-03-03 00:00:00
3   2022-04-04 00:00:00
4   2022-05-05 00:00:00
5   2022-06-06 12:20:00
dtype: datetime64[ns]

# Задача №10

In [65]:
# Объект pandas.Series (переменная s1) содержит некоторые числовые значения. 
# Для значений хранящихся в s2 определите индексы под которыми они хранятся  
# в s1. Функция должна вернуть список (python list):
    
# [5, 4, 0, 8]

s1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
s2 = pd.Series([1, 3, 10, 13])

In [66]:
s1

0    10
1     9
2     6
3     5
4     3
5     1
6    12
7     8
8    13
dtype: int64

In [67]:
s2

0     1
1     3
2    10
3    13
dtype: int64

In [68]:
s2.values

array([ 1,  3, 10, 13], dtype=int64)

In [6]:
lst = []
for i in s2:
    lst += (s1[s1 == i].index.to_list())

In [7]:
lst

[5, 4, 0, 8]

In [8]:
# Внимание правильный ответ:

list(pd.Index(s1).get_indexer(s2))

[5, 4, 0, 8]

In [9]:
# get_indexer работает с pd.Index

pd.Index(s1)

Int64Index([10, 9, 6, 5, 3, 1, 12, 8, 13], dtype='int64')

In [14]:
# передавать в get_indexer надо коллекцию например так [10]

pd.Index(s2).get_indexer([10])

array([2], dtype=int64)

In [ ]:
28.05.2023

# Задача № 11

In [4]:
# Даны следующие ряды данных:

# s_forecast - ряд прогнозных значений

# s_real - ряд фактических значений
 

# Вычислите среднеквадратичную ошибку.


s_forecast = pd.Series(range(10))
s_real  = pd.Series(reversed(range(10)))


In [10]:
s1 = s_forecast
s1

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [11]:
s2 = s_real
s2

0    9
1    8
2    7
3    6
4    5
5    4
6    3
7    2
8    1
9    0
dtype: int64

In [ ]:
# Среднеквадратичная ошибка (Mean Squared Error) – Среднее арифметическое (Mean) 
# квадратов разностей между предсказанными и реальными значениями Модели (Model) 
# Машинного обучения (ML):

# MSE позволяет оценить, насколько хорошо модель приближает истинные значения. 
# Чем меньше значение MSE, тем ближе предсказания модели к истинным значениям.

In [14]:
((s1 - s2)**2).mean()

33.0

# Задача № 12

In [50]:
# Измените первый символ каждого слова на верхний регистр.

s1 = pd.Series(['the', 'weather', 'is', 'fine']) 

In [23]:
s1[0][0]

't'

In [37]:
# с циклом:
for i in range(len(s1)):
    s1[i] = np.char.replace(s1[i], s1[i][0], s1[i][0].upper())

In [38]:
s1

0        The
1    Weather
2         Is
3       Fine
dtype: object

In [ ]:
# без цикла

In [53]:
s1.str.capitalize()

0        The
1    Weather
2         Is
3       Fine
dtype: object

# Задача №13

In [66]:
# Подсчитайте количество символов в каждом слове. Функция solution должна вернуть серию.

s1 = pd.Series(['the', 'weather', 'is', 'fine'])

In [77]:
result = pd.Series(s1.str.len())
result

0    3
1    7
2    2
3    4
dtype: int64

In [ ]:
20.06.2023

# Задача №14

In [ ]:
# Вытяните день месяца, номер недели, день года и день недели из серии (s1)

# Date:  [5, 4, 3, 4, 5, 6]
# Week number:  [1, 5, 13, 22, 9, 9]
# Day number of year:  [5, 35, 93, 155, 64, 65]
# Day of week:  ['Tuesday', 'Thursday', 'Saturday', 'Friday', 'Friday', 'Saturday']

In [69]:
s1 = pd.Series(['05 Jan 2021', '02-04-2021', '20210403', '2021/06/04', '2021-03-05', '2021-03-06T12:20'])

In [91]:
print('Date: ', list(pd.to_datetime(s1).dt.day))

print('Week number: ', list(pd.to_datetime(s1).dt.isocalendar().week))

print('Day number of year: ', list(pd.to_datetime(s1).dt.dayofyear))

print('Day of week: ', list(pd.to_datetime(s1).dt.day_name()))

Date:  [5, 4, 3, 4, 5, 6]
Week number:  [1, 5, 13, 22, 9, 9]
Day number of year:  [5, 35, 93, 155, 64, 65]
Day of week:  ['Tuesday', 'Thursday', 'Saturday', 'Friday', 'Friday', 'Saturday']


# Задача №15

In [ ]:
# Измените даты лежащие в серии (s1) таким образом чтобы они начинались с 10-го числа соответствующего месяца.

# Требуемый финальный результат (наполнение):
# 0   2022-01-10
# 1   2022-02-10
# 2   2022-03-10
# dtype: datetime64[ns]

In [110]:
s1 = pd.Series(['Jan 2022', 'Feb 2022', 'Mar 2022'])

In [93]:
s1

0    Jan 2022
1    Feb 2022
2    Mar 2022
dtype: object

In [96]:
pd.to_datetime(s1)

0   2022-01-01
1   2022-02-01
2   2022-03-01
dtype: datetime64[ns]

In [101]:
pd.to_datetime(s1).dt.year

0    2022
1    2022
2    2022
dtype: int64

In [102]:
pd.to_datetime(s1).dt.month

0    1
1    2
2    3
dtype: int64

In [114]:
df = pd.DataFrame({'year': list(pd.to_datetime(s1).dt.year),
                   'month': list(pd.to_datetime(s1).dt.month),
                   'day': [10 for i in range (len(s1))]})

In [115]:
df

year  month  day
0  2022      1   10
1  2022      2   10
2  2022      3   10

In [117]:
pd.to_datetime(df)

0   2022-01-10
1   2022-02-10
2   2022-03-10
dtype: datetime64[ns]

### Несколько вариантов решения этой задачи из комментариев:

### Вариант №1

In [120]:
# Шаг 1. Преобразуем изначальную серию old_series в серию с датами new_series:
new_series = pd.to_datetime(s1)

In [121]:
new_series

0   2022-01-01
1   2022-02-01
2   2022-03-01
dtype: datetime64[ns]

In [122]:
# Шаг 2. Создадим значение количества дней, на которое нужно изменить new_serias:
days_amount = pd.Timedelta(days=9)

In [125]:
days_amount

Timedelta('9 days 00:00:00')

In [123]:
# Шаг 3. Преобразуем new_series в финальную с нужной датой final_series:
final_series = new_series + days_amount

In [126]:
final_series

0   2022-01-10
1   2022-02-10
2   2022-03-10
dtype: datetime64[ns]

### Вариант№2

In [127]:
s1

0    Jan 2022
1    Feb 2022
2    Mar 2022
dtype: object

In [138]:
s11 = pd.to_datetime(s1)

In [152]:
s11

0   2022-01-01
1   2022-02-01
2   2022-03-01
dtype: datetime64[ns]

In [154]:
s11.apply(lambda x: x.replace(day=10))

0   2022-01-10
1   2022-02-10
2   2022-03-10
dtype: datetime64[ns]

In [157]:
s11[0].replace(day=10)

Timestamp('2022-01-10 00:00:00')

In [ ]:
26.06.2023

# Задача №16

In [138]:
# Из серии (s1) вытяните слова, содержащие не менее 2 гласных.

# Сложность: 💪💪💪 
    
s1 = pd.Series(['Apple', 'Orange', 'Plan', 'Sky', 'Money'])

In [69]:
vow = ['a', 'e', 'i', 'o', 'u']

In [37]:
s1.apply(lambda x: x in vow)

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [136]:
lst = []
lst_index = []
def calc_vows(x):    
    cnt = 0
    for i in vow:
        if i in x.lower():
            cnt +=1
            if cnt >= 2:
                lst.append(x)
                lst_index.append()
                break
    return lst

In [133]:
lst

['Apple', 'Orange', 'Money']

In [135]:
lst_index

[<function str.index>, <function str.index>, <function str.index>]

In [121]:
pd.Series(lst)

0     Apple
1    Orange
2     Money
dtype: object

In [150]:
import pandas as pd
import numpy as np

lst = []
vow = ['a', 'e', 'i', 'o', 'u']
def calc_vows(x):    
    cnt = 0
    for i in vow:
        if i in x.lower():
            cnt +=1
            if cnt >= 2:
                lst.append(x)
                break
    return lst


def solution():
    s1 = pd.Series(['Apple', 'Orange', 'Plan', 'Sky', 'Money'])
    
    s1.apply(lambda x: calc_vows(x))
    result = pd.Series(list(lst), index = [pd.Index(s1).get_indexer(lst)])
    return result

In [151]:
solution()

0     Apple
1    Orange
4     Money
dtype: object

In [2]:
# Внимание правильное решение:

import pandas as pd
import numpy as np

s1 = pd.Series(['Apple', 'Orange', 'Plan', 'Sky', 'Money'])
s2 = s1.str.count('[aeiouyAEIOUY]')

print(s1[s2 >= 2])

0     Apple
1    Orange
4     Money
dtype: object


In [162]:
s1.str.count('[aeiouyAEIOUY]')

0    2
1    3
2    1
3    1
4    3
dtype: int64

In [ ]:
27.06.2023

# Задача №17

In [ ]:
# Сложность: 💪💪💪 

# Извлеките корректные почтовые адреса из серии (s1). Используйте pattern для этой задачи.

# Требуемый финальный результат (наполнение):
# 1          help@stepik.com
# 2                user@t.co
# 3    lovepandas@google.com
# dtype: object

In [14]:
# import pandas as pd
# import numpy as np

# def solution():
#     s1 = pd.Series(['teach pandas at stepik.com', 'help@stepik.com', 'user@t.co', 'lovepandas@google.com'])
#     pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
#     result = # ваш код здесь)
#     return result

In [16]:
s1 = pd.Series(['teach pandas at stepik.com', 'help@stepik.com', 'user@t.co', 'lovepandas@google.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

In [44]:
# И снова рубрика "небольшие подсказки".
# Шаг 1. Воспользуемся супер функций pandas.Series.str.findall (спасибо Роману Медведеву за подсказку),
# эта функция принимает в себя аргумент в виде паттерна (или регулярное выражение), а возвращает все
# совпадения с этим паттерном каждой строки серии. Т.е. если не будет совпадения, 
# то функция вернут пустой список.

s = s1.str.findall(pattern)
s

0                         []
1          [help@stepik.com]
2                [user@t.co]
3    [lovepandas@google.com]
dtype: object

In [50]:
ss = s[s.str.len() != 0]
ss

1          [help@stepik.com]
2                [user@t.co]
3    [lovepandas@google.com]
dtype: object

In [52]:
# Избавимся от квадратных скобок. Нам поможет функция pandas.Series.explode,
# которая ничего не принимает в виде аргумента, а возвращает dtype строк 
# подмножества в виде object. Нам это и нужно.
# код:
# s4 = s3.explode()

In [53]:
ss.explode()

1          help@stepik.com
2                user@t.co
3    lovepandas@google.com
dtype: object

In [49]:
result = ss.apply(lambda x: x[0])
result

1          help@stepik.com
2                user@t.co
3    lovepandas@google.com
dtype: object

In [51]:
s[s.str.len() != 0].apply(lambda x: x[0])

1          help@stepik.com
2                user@t.co
3    lovepandas@google.com
dtype: object

# Задача №18

In [5]:
# Сложность: 💪💪 
    
# Вычислите среднее значение веса каждого фрукта.

# Требуемый финальный результат (наполнение):
# apple     6.0
# banana    4.0
# carrot    5.8
# dtype: float64
    
    
import pandas as pd
import numpy as np

def solution():
    fruit_list = ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']
    weights_list =  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]

    fruits = pd.Series(fruit_list)
    weights = pd.Series(weights_list)

    #result = # ваш код здесь)
    return result

In [8]:
df = pd.DataFrame()

fruit_list = ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']
weights_list =  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]

In [9]:
df['fruit_list'] = fruit_list
df['weights_list'] = weights_list

In [10]:
df

fruit_list  weights_list
0     banana           1.0
1     carrot           2.0
2      apple           3.0
3     carrot           4.0
4     carrot           5.0
5      apple           6.0
6     banana           7.0
7     carrot           8.0
8      apple           9.0
9     carrot          10.0

In [26]:
df_group = df.groupby('fruit_list')['weights_list'].mean()
df_group

fruit_list
apple     6.0
banana    4.0
carrot    5.8
Name: weights_list, dtype: float64

In [28]:
df_group.name = None

In [33]:
df_group.index.name = None

In [34]:
df_group

apple     6.0
banana    4.0
carrot    5.8
dtype: float64

In [25]:
s = pd.Series(df_group.weights_list, index = df_group.index)
s

fruit_list
apple     6.0
banana    4.0
carrot    5.8
Name: weights_list, dtype: float64

In [ ]:
import pandas as pd
import numpy as np

def solution():
    fruit_list = ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']
    weights_list =  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]

    fruits = pd.Series(fruit_list)
    weights = pd.Series(weights_list)
    
    df = pd.DataFrame()
    df['fruit_list'] = fruit_list
    df['weights_list'] = weights_list
    
    df_group = df.groupby('fruit_list')['weights_list'].mean()
    df_group.name = None
    df_group.index.name = None
        
    return df_group

In [ ]:
# ПРАВИЛЬНЫЙ ОТВЕТ:
    
import pandas as pd
import numpy as np

fruit_list = ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']
weights_list =  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]

fruits = pd.Series(fruit_list)
weights = pd.Series(weights_list)
print(weights.groupby(fruits).mean())

In [2]:
# 08/07/2023

# Задача №19

In [3]:
# Вычислить евклидово расстояние между рядами (точками) X и Y

X = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
Y = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
# Расстояние Евклида — это геометрическое расстояние в многомерном пространстве. Оно вычисляется по теореме Пифагора.

# https://wiki.loginom.ru/articles/euclid-distance.html

In [16]:
df = pd.DataFrame([X, Y])

In [18]:
df = df.T

In [20]:
df.columns = ['X', 'Y']

In [22]:
df['Raznost'] = df.X - df.Y

In [29]:
df['R2'] = df['Raznost'].apply(lambda x: x**2)

In [36]:
df

X   Y  Raznost  R2
0   1  10       -9  81
1   2   9       -7  49
2   3   8       -5  25
3   4   7       -3   9
4   5   6       -1   1
5   6   5        1   1
6   7   4        3   9
7   8   3        5  25
8   9   2        7  49
9  10   1        9  81

In [31]:
rast_evklid = np.sqrt(sum(df.R2))

In [32]:
rast_evklid

18.16590212458495

In [38]:
X

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [39]:
Y

0    10
1     9
2     8
3     7
4     6
5     5
6     4
7     3
8     2
9     1
dtype: int64

In [51]:
np.sqrt(sum((X - Y)**2))

18.16590212458495

In [54]:
# Внимание - правильный ответ на эту задачу:
    
print(np.linalg.norm(X - Y))

d = sum(list(map(lambda x, y: (x - y)**2, X, Y)))**0.5
print(d)


In [56]:
pd.Series(map(lambda x,y: (x - y), X, Y))

0   -9
1   -7
2   -5
3   -3
4   -1
5    1
6    3
7    5
8    7
9    9
dtype: int64

# Задача №20

In [ ]:
# В серии (s1) находятся даты с 1 по 8 января 2022 года. 
# Однако некоторые даты и значения к датам пропущены.
# Сделайте так, чтобы все отсутствующие даты отображались 
# и заполнялись значением из предыдущей даты.

In [2]:
s1 = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2022-01-01', '2022-01-03', '2022-01-06', '2022-01-08']))

In [38]:
s1

2022-01-01     1.0
2022-01-03    10.0
2022-01-06     3.0
2022-01-08     NaN
dtype: float64

In [40]:
# пропуски в датах можно заполнить так:
s11 = s1.asfreq(freq='D')
s11

2022-01-01     1.0
2022-01-02     NaN
2022-01-03    10.0
2022-01-04     NaN
2022-01-05     NaN
2022-01-06     3.0
2022-01-07     NaN
2022-01-08     NaN
Freq: D, dtype: float64

In [14]:
# я же использую как обычно более сложный путь:
rng = pd.date_range('1/1/2022', periods=8, freq='D')

In [35]:
s2 = pd.Series(0*8, index = rng)
s2

2022-01-01    0
2022-01-02    0
2022-01-03    0
2022-01-04    0
2022-01-05    0
2022-01-06    0
2022-01-07    0
2022-01-08    0
Freq: D, dtype: int64

In [36]:
s3 = s2 + s1
s3

2022-01-01     1.0
2022-01-02     NaN
2022-01-03    10.0
2022-01-04     NaN
2022-01-05     NaN
2022-01-06     3.0
2022-01-07     NaN
2022-01-08     NaN
dtype: float64

In [37]:
s3.ffill()

2022-01-01     1.0
2022-01-02     1.0
2022-01-03    10.0
2022-01-04    10.0
2022-01-05    10.0
2022-01-06     3.0
2022-01-07     3.0
2022-01-08     3.0
dtype: float64

# Задача №21

In [ ]:
# Отредактируйте название колонок датафрейма (df) следующим образом:

# 1. user -> user_name

# 2. все точки в названии колонок заменить нижним подчёркиванием

In [12]:
df = pd.DataFrame(data = {'user' : ['Ivan', 'Petr', 'Alex'], 
                          'user.balance' : [500, 200, 0], 
                          'user.age' : [34, 25, 18], 
                          'user.group' : ['A', 'B', 'A']})

In [13]:
df

user  user.balance  user.age user.group
0  Ivan           500        34          A
1  Petr           200        25          B
2  Alex             0        18          A

In [14]:
df.columns = df.columns.str.replace('.', '_')

C:\Users\roman\AppData\Local\Temp\ipykernel_69960\2262415099.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df.columns = df.columns.str.replace('.', '_')


In [21]:
df.columns = ['user_name', 'user_balance', 'user_age', 'user_group']

# Задача № 22

In [ ]:
# Проверьте, имеются ли пропущенные значения в датафрейме (df). 

# Если в строке датафрейма есть хотя-бы одно пропущенное значение - верните True иначе False.

# Рекомендация:

# pandas.isnull

# pandas.DataFrame.any

In [2]:
df = pd.DataFrame(data = {'user' : ['Ivan', 'Petr', 'Alex'], 'user.balance' : [500, None, 0], 'user.age' : [34, 25, 18], 'user.group' : ['A', 'B', 'A']})

In [3]:
df

user  user.balance  user.age user.group
0  Ivan         500.0        34          A
1  Petr           NaN        25          B
2  Alex           0.0        18          A

In [7]:
df.isnull()

user  user.balance  user.age  user.group
0  False         False     False       False
1  False          True     False       False
2  False         False     False       False

In [12]:
df.isnull().any(axis = 1)

0    False
1     True
2    False
dtype: bool

# Задача № 23

In [14]:
# Подсчитайте количество пропущенных значений в каждом столбце.

df = pd.DataFrame(data = {'user' : ['Ivan', 'Petr', 'Alex', 'Den'], 'user.balance' : [500, None, 0, None], 'user.age' : [34, None, 18, 43], 'user.group' : ['A', 'B', 'A', 'B']})

In [15]:
df

user  user.balance  user.age user.group
0  Ivan         500.0      34.0          A
1  Petr           NaN       NaN          B
2  Alex           0.0      18.0          A
3   Den           NaN      43.0          B

In [16]:
df.isna().sum()

user            0
user.balance    2
user.age        1
user.group      0
dtype: int64

# Задача № 24

In [4]:
# Замените отсутствующие значения в столбцах user.speed и user.bag_weight их соответствующими средними значениями.

df = pd.DataFrame(data = {'user' : ['Ivan', 'Petr', 'Alex', 'Den'],
                          'user.speed' : [40, None, 42, 35],
                          'user.bag_weight' : [8, None, 2, 4]})

In [5]:
df

user  user.speed  user.bag_weight
0  Ivan        40.0              8.0
1  Petr         NaN              NaN
2  Alex        42.0              2.0
3   Den        35.0              4.0

In [10]:
df['user.speed'].mean()

39.0

In [11]:
df['user.speed'].fillna(df['user.speed'].mean())

0    40.0
1    39.0
2    42.0
3    35.0
Name: user.speed, dtype: float64

In [12]:
df['user.bag_weight'].fillna(df['user.bag_weight'].mean())

0    8.000000
1    4.666667
2    2.000000
3    4.000000
Name: user.bag_weight, dtype: float64

In [13]:
df

user  user.speed  user.bag_weight
0  Ivan        40.0              8.0
1  Petr         NaN              NaN
2  Alex        42.0              2.0
3   Den        35.0              4.0

# Задача № 25

In [114]:
# Используйте метод apply, чтобы заменить отсутствующие значения в user.speed средним значением столбца,
# а в user.bag_weight — медианой столбца.

# Попытайтесь в ответе использовать apply всего 1 раз.

df = pd.DataFrame(data = {'user' : ['Ivan', 'Petr', 'Alex', 'Den'],
                          'user.speed' : [40, None, 42, 35],
                          'user.bag_weight' : [8, None, 2, 4]})

In [115]:
df

user  user.speed  user.bag_weight
0  Ivan        40.0              8.0
1  Petr         NaN              NaN
2  Alex        42.0              2.0
3   Den        35.0              4.0

In [116]:
df.apply(lambda x: x.fillna(df['user.speed'].mean()) if x.name in ['user.speed'] else x.fillna(df['user.bag_weight'].median()))

user  user.speed  user.bag_weight
0  Ivan        40.0              8.0
1  Petr        39.0              4.0
2  Alex        42.0              2.0
3   Den        35.0              4.0

# Задача № 26

In [2]:
# Поменяйте столбцы А и Е местами в датафрейме:


df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

In [3]:
df

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [4]:
df.columns

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [5]:
df.columns = ['e', 'b', 'c', 'd', 'a']

In [6]:
df

e   b   c   d   a
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [9]:
df.reindex(['e', 'b', 'c', 'd', 'a'], axis = 1)

e   b   c   d   a
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [11]:
# Варианты от мастеров:

df = df[list('ebcda')]
# print(df)

In [ ]:
print(df.iloc[:,[4,1,2,3,0]])

In [ ]:
df.reindex(columns = ["e", "b", "c", "d", "a"])

In [ ]:
df = df.reindex(columns=list('ebcda'))

In [12]:
print(df[list('ebcda')])

    e   b   c   d   a
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19


# Задача № 27

In [42]:
# Поменяйте порядок столбцов в датафрейме от Е до А.

df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
df

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [34]:
cols = list(df.columns)

In [35]:
cols.reverse()

In [47]:
cols

['e', 'd', 'c', 'b', 'a']

In [37]:
df.columns = cols

In [48]:
df[cols]

e   d   c   b   a
0   4   3   2   1   0
1   9   8   7   6   5
2  14  13  12  11  10
3  19  18  17  16  15

# Задача № 28

In [2]:
# Выведите на экран строки датафрейма с шагом 2.

df = pd.DataFrame(data = {'user' : ['Ivan', 'Petr', 'Alex', 'Den', 'Viktor'], 
                          'user.speed' : [40, None, 42, 35, 60], 
                          'user.bag_weight' : [8, None, 2, 4, 19]})

In [3]:
df

user  user.speed  user.bag_weight
0    Ivan        40.0              8.0
1    Petr         NaN              NaN
2    Alex        42.0              2.0
3     Den        35.0              4.0
4  Viktor        60.0             19.0

In [14]:
df.iloc[lambda x: x.index % 2 == 0]

user  user.speed  user.bag_weight
0    Ivan        40.0              8.0
2    Alex        42.0              2.0
4  Viktor        60.0             19.0

# Задача № 29

In [2]:
# Создайте составной индекс на основе колонок user и user.number для датафрейма:


df = pd.DataFrame(data = {'user' : ['Ivan', 'Petr', 'Alex', 'Den', 'Viktor'],
                          'user.number' : ['222-333', None, '222-555', '222-666', '222-777'],
                          'user.speed' : [40, None, 42, 35, 60],
                          'user.bag_weight' : [8, None, 2, 4, 19]})

In [70]:
df['user.number'] = df['user.number'].fillna('missing')

In [71]:
df

user user.number  user.speed  user.bag_weight
0    Ivan     222-333        40.0              8.0
1    Petr     missing         NaN              NaN
2    Alex     222-555        42.0              2.0
3     Den     222-666        35.0              4.0
4  Viktor     222-777        60.0             19.0

In [72]:
df['ind'] = df['user'].str.title() + '_' + df['user.number'].str.lower()

In [74]:
df

user user.number  user.speed  user.bag_weight             ind
0    Ivan     222-333        40.0              8.0    Ivan_222-333
1    Petr     missing         NaN              NaN    Petr_missing
2    Alex     222-555        42.0              2.0    Alex_222-555
3     Den     222-666        35.0              4.0     Den_222-666
4  Viktor     222-777        60.0             19.0  Viktor_222-777

In [75]:
df = df.set_index('ind')

In [79]:
df.index.name = None

In [80]:
df

user user.number  user.speed  user.bag_weight
Ivan_222-333      Ivan     222-333        40.0              8.0
Petr_missing      Petr     missing         NaN              NaN
Alex_222-555      Alex     222-555        42.0              2.0
Den_222-666        Den     222-666        35.0              4.0
Viktor_222-777  Viktor     222-777        60.0             19.0

# Задача №30

In [3]:
# Как задать максимальное количество выводимых строк датафрейма?

df

user user.number  user.speed  user.bag_weight
0    Ivan     222-333        40.0              8.0
1    Petr        None         NaN              NaN
2    Alex     222-555        42.0              2.0
3     Den     222-666        35.0              4.0
4  Viktor     222-777        60.0             19.0

In [22]:
pd.set_option('display.max_rows', 20)

In [8]:
df

user user.number  user.speed  user.bag_weight
0     Ivan     222-333        40.0              8.0
..     ...         ...         ...              ...
4   Viktor     222-777        60.0             19.0

[5 rows x 4 columns]

In [ ]:
# Sets the value of the specified option.

# Available options: ...

# https://pandas.pydata.org/docs/reference/api/pandas.set_option.html?highlight=set_option#pandas.set_option

# Задача № 31

In [14]:
# Для столбца А найдите индекс строки в которой находится второе наибольшее значение.

df = pd.DataFrame([[16,24,29],[1,10,16],[26,21,10],[3,3,8],
                   [6,17,17],[2,25,14],[9,13,21],[27,24,17],[19,29,1],[20,24,6]], columns=list('abc'))



In [23]:
df

a   b   c
0  16  24  29
1   1  10  16
2  26  21  10
3   3   3   8
4   6  17  17
5   2  25  14
6   9  13  21
7  27  24  17
8  19  29   1
9  20  24   6

In [33]:
df['a'].sort_values(ascending = False).index[1]

2

# Задача № 32

In [19]:
# Выведите последние две строки датафрейма, сумма ячеек которых больше 100.


import pandas as pd
import numpy as np

df = pd.DataFrame([[23,33,16,35],
                   [24,20,13,10],
                   [32,33,30,28],
                   [13,32,36,18],
                   [25,27,31,10],
                   [35,13,36,21],
                   [32,32,25,17],
                   [34,24,23,19]])

In [22]:
df2 = df[df.sum(axis = 1) > 100]

In [25]:
df2.iloc[[-2,-1]]

0   1   2   3
5  35  13  36  21
6  32  32  25  17

# Задача № 33

In [2]:
import pandas as pd
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

In [3]:
df.head(3)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

In [4]:
# Выведите на экран данные, которые хранятся в строках [3, 4, 8] и колонках ['animal', 'age'].

In [17]:
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [24]:
df.columns

Index(['animal', 'age', 'visits', 'priority'], dtype='object')

In [27]:
col_args = []
for i in range(len(df.columns)):
    if df.columns[i] in ['animal', 'age']:
        col_args.append(i)

In [28]:
col_args

[0, 1]

In [29]:
df.iloc[[3, 4, 8], col_args]

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

In [5]:
df.iloc[[3, 4, 8]][['animal', 'age']]

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

In [ ]:
# Выберите только те строки, в которых количество посещений (visits) больше 2.

In [6]:
df[df['visits'] > 2]

animal  age  visits priority
b    cat  3.0       3      yes
d    dog  NaN       3      yes
f    cat  2.0       3       no

In [ ]:
# Выберите строки датафрейма  в которых animal = cat, а age < 3.

In [7]:
df[(df['animal'] == 'cat') & (df['age'] <3)]

animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

In [ ]:
# В строке f замените значение в колонке age на 1.5

In [29]:
df.loc['f'].replace(2, 1.5)

animal      cat
age         1.5
visits        3
priority     no
Name: f, dtype: object

In [31]:
df.loc['f'] = df.loc['f'].replace(2, 1.5)

In [34]:
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [33]:
# Посчитайте итоговое количество посещений (visits)

In [35]:
df.visits.sum()

19

In [36]:
# Посчитайте средний возраст каждого вида животного (animal)

In [41]:
df.groupby('animal')['age'].agg('mean')

animal
cat      2.5
dog      5.0
snake    2.5
Name: age, dtype: float64

In [43]:
# Отсортируйте датафрейм по столбцу age в порядке убывания, а затем по столбцу visits в порядке возрастания.

In [74]:
df.sort_values(by = ['visits']).sort_values(by = ['age'], ascending = False)

animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  2.0       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes

In [59]:
df.sort_values(['visits','age'])

animal  age  visits priority
a    cat  2.5       1      yes
j    dog  3.0       1       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
c  snake  0.5       2       no
e    dog  5.0       2       no
i    dog  7.0       2       no
f    cat  2.0       3       no
b    cat  3.0       3      yes
d    dog  NaN       3      yes

In [3]:
# Столбец priority содержит строковые значения yes и no. Замените их на булевы True и False

In [6]:
df['priority'] = np.where(df['priority'] == 'yes', True, False)

In [7]:
df

animal  age  visits  priority
a    cat  2.5       1      True
b    cat  3.0       3      True
c  snake  0.5       2     False
d    dog  NaN       3      True
e    dog  5.0       2     False
f    cat  2.0       3     False
g  snake  4.5       1     False
h    cat  NaN       1      True
i    dog  7.0       2     False
j    dog  3.0       1     False

In [19]:
# Определите средний возраст для каждого типа животного и количества посещений.

# (Другими словами, постройте сводную таблицу, где каждая строка — это тип животного,
#  каждый столбец — количество посещений, а значения — средний возраст).

df1 = df.groupby(['animal', 'visits'])['age'].agg('mean')

In [24]:
df2 = df1.to_frame()

In [28]:
df3 = df2.reset_index()

In [31]:
df3

animal  visits  age
0    cat       1  2.5
1    cat       3  2.5
2    dog       1  3.0
3    dog       2  6.0
4    dog       3  NaN
5  snake       1  4.5
6  snake       2  0.5

In [32]:
df3.pivot(index='animal', columns='visits', values='age')

visits    1    2    3
animal               
cat     2.5  NaN  2.5
dog     3.0  6.0  NaN
snake   4.5  0.5  NaN

# Задача № 34

In [33]:
# Вычтите среднее значение строки из каждого элемента в строке.

import pandas as pd
import numpy as np

df = pd.DataFrame([[0.020448, 0.456925, 0.992258], [0.743399, 0.555486, 0.089364], [0.094699, 0.283184, 0.216221]])

In [51]:
df

0         1         2
0  0.020448  0.456925  0.992258
1  0.743399  0.555486  0.089364
2  0.094699  0.283184  0.216221

In [40]:
df.mean(axis = 1)

0    0.489877
1    0.462750
2    0.198035
dtype: float64

In [41]:
df - df.mean(axis = 1)

0         1         2
0 -0.469429 -0.005825  0.794223
1  0.253522  0.092736 -0.108671
2 -0.395178 -0.179566  0.018186

In [ ]:
0 -0.469429 -0.032952  0.502381
1  0.280649  0.092736 -0.373386
2 -0.103336  0.085149  0.018186

In [48]:
df.loc[0] - df.loc[0].mean()

0   -0.469429
1   -0.032952
2    0.502381
Name: 0, dtype: float64

In [60]:
df.loc[[0,1,2]]

0         1         2
0  0.020448  0.456925  0.992258
1  0.743399  0.555486  0.089364
2  0.094699  0.283184  0.216221

In [61]:
df.loc[[0,1,2]] - df.loc[[0,1,2]].mean()

0         1         2
0 -0.265734  0.025060  0.559644
1  0.457217  0.123621 -0.343250
2 -0.191483 -0.148681 -0.216393

In [64]:
df.apply(lambda x: x - x.mean(), axis = 1)

0         1         2
0 -0.469429 -0.032952  0.502381
1  0.280649  0.092736 -0.373386
2 -0.103336  0.085149  0.018186

# Задача № 35

In [ ]:
# В каком столбце чисел сумма наименьшая? Выведите на экран название этого столбца.

In [2]:
df = pd.DataFrame([[0.020448, 0.456925, 0.992258], [0.743399, 0.555486, 0.089364], [0.094699, 0.283184, 0.216221]], columns=list('abc'))

In [51]:
df

a         b         c
0  0.020448  0.456925  0.992258
1  0.743399  0.555486  0.089364
2  0.094699  0.283184  0.216221

In [52]:
df.sum().min()

0.858546

In [53]:
df.columns

Index(['a', 'b', 'c'], dtype='object')

In [56]:
ans = df.columns[df.sum() == df.sum().min()]

In [63]:
ans

Index(['a'], dtype='object')

In [70]:
ans.item()

'a'

In [87]:
# Как подсчитать, сколько уникальных строк имеет датафрейм (т. е. игнорировать все повторяющиеся строки)?

df = pd.DataFrame([[0.020448, 0.456925, 0.992258],
                   [0.743399, 0.555486, 0.089364],
                   [0.020448, 0.456925, 0.992258],
                   [0.094699, 0.283184, 0.216221]],
                  columns=list('abc'))

In [88]:
df

a         b         c
0  0.020448  0.456925  0.992258
1  0.743399  0.555486  0.089364
2  0.020448  0.456925  0.992258
3  0.094699  0.283184  0.216221

In [103]:
df[df.duplicated(keep = False)].shape[0]

2

# Задача № 36

In [106]:
# Имеется датафрейм состоящий из 10 столбцов чисел с плавающей запятой. 
# Ровно 5 записей в каждой строке являются значениями NaN. 
# Для каждой строки датафрейма найдите столбец, содержащий третье значение NaN.

In [2]:
nan = np.nan

data = [[0.04,  nan,  nan, 0.25,  nan, 0.43, 0.71, 0.51,  nan,  nan],
        [ nan,  nan,  nan, 0.04, 0.76,  nan,  nan, 0.67, 0.76, 0.16],
        [ nan,  nan, 0.5 ,  nan, 0.31, 0.4 ,  nan,  nan, 0.24, 0.01],
        [0.49,  nan,  nan, 0.62, 0.73, 0.26, 0.85,  nan,  nan,  nan],
        [ nan,  nan, 0.41,  nan, 0.05,  nan, 0.61,  nan, 0.48, 0.68]]

columns = list('abcdefghij')

df = pd.DataFrame(data, columns=columns)

In [7]:
df

a   b     c     d     e     f     g     h     i     j
0  0.04 NaN   NaN  0.25   NaN  0.43  0.71  0.51   NaN   NaN
1   NaN NaN   NaN  0.04  0.76   NaN   NaN  0.67  0.76  0.16
2   NaN NaN  0.50   NaN  0.31  0.40   NaN   NaN  0.24  0.01
3  0.49 NaN   NaN  0.62  0.73  0.26  0.85   NaN   NaN   NaN
4   NaN NaN  0.41   NaN  0.05   NaN  0.61   NaN  0.48  0.68

In [4]:
df.columns

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')

In [10]:
df1 = df.isna()*1

In [11]:
df1

a  b  c  d  e  f  g  h  i  j
0  0  1  1  0  1  0  0  0  1  1
1  1  1  1  0  0  1  1  0  0  0
2  1  1  0  1  0  0  1  1  0  0
3  0  1  1  0  0  0  0  1  1  1
4  1  1  0  1  0  1  0  1  0  0

In [12]:
len(df1)

5

In [45]:
lst = []
summa = 0

for i in range(len(df1)):
    summa = 0
    for j in range(-1, len(df1.columns)-1):

        summa = summa + df1.iloc[i][j + 1]
#         print(summa)
        if summa == 3:
#             print(df1.columns[[j + 1]])
            lst.append(df1.columns[[j + 1]].item())
            break
            

In [48]:
ans = pd.Series(lst)

In [49]:
ans

0    e
1    c
2    d
3    h
4    d
dtype: object

In [52]:
# Ответ в одну строку:

print(pd.DataFrame(df.isna().cumsum(axis=1) == 3).idxmax(1))

0    e
1    c
2    d
3    h
4    d
dtype: object


In [54]:
df1.cumsum(axis = 1) == 3

a      b      c      d      e      f      g      h      i      j
0  False  False  False  False   True   True   True   True  False  False
1  False  False   True   True   True  False  False  False  False  False
2  False  False  False   True   True   True  False  False  False  False
3  False  False  False  False  False  False  False   True  False  False
4  False  False  False   True   True  False  False  False  False  False

In [56]:
# Еще один ответ в одну строку:

df.apply(lambda x: x[x.isnull()].index[2],axis=1)

0    e
1    c
2    d
3    h
4    d
dtype: object

In [70]:
df

a   b     c     d     e     f     g     h     i     j
0  0.04 NaN   NaN  0.25   NaN  0.43  0.71  0.51   NaN   NaN
1   NaN NaN   NaN  0.04  0.76   NaN   NaN  0.67  0.76  0.16
2   NaN NaN  0.50   NaN  0.31  0.40   NaN   NaN  0.24  0.01
3  0.49 NaN   NaN  0.62  0.73  0.26  0.85   NaN   NaN   NaN
4   NaN NaN  0.41   NaN  0.05   NaN  0.61   NaN  0.48  0.68

In [73]:
df.apply(lambda x: x[x.isnull()].index[0], axis = 1)

0    b
1    a
2    a
3    b
4    a
dtype: object

# Задача № 37

In [ ]:
# Датафрейм содержит колонку grps (название некоторой группы) и колонку целочисленных значений vals.
# Для каждой группы найдите сумму трех наибольших значений.

In [2]:
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'), 
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})

In [3]:
df

grps  vals
0     a    12
1     a   345
2     a     3
3     b     1
4     b    45
5     c    14
6     a     4
7     a    52
8     b    54
9     c    23
10    c   235
11    c    21
12    b    57
13    b     3
14    c    87

In [20]:
df1 = df.sort_values(by = ['grps', 'vals'], ascending = [True, False])

In [21]:
df1

grps  vals
1     a   345
7     a    52
0     a    12
6     a     4
2     a     3
12    b    57
8     b    54
4     b    45
13    b     3
3     b     1
10    c   235
14    c    87
9     c    23
11    c    21
5     c    14

In [23]:
df1.groupby('grps')['vals'].agg(lambda x: x.head(3).sum())

grps
a    409
b    156
c    345
Name: vals, dtype: int64

# Задача № 38

In [40]:
# Датафрейм df имеет два целочисленных столбца «A» и «B». 
# Значения в «A» находятся в диапазоне от 1 до 100 (включительно).

# Для каждой группы из 10 последовательных целых чисел в столбце А (т. е. (0, 10], (10, 20], ...) 
# вычислите сумму соответствующих значений в столбце B.

In [115]:
df = pd.DataFrame(np.random.RandomState(8765).randint(1, 101, size=(100, 2)), columns = ["A", "B"])

In [116]:
df

A   B
0   46  29
1   75  22
2   49  63
3   33  43
4   71  75
..  ..  ..
95  60  87
96  57  40
97  86  19
98  50  56
99  97  94

[100 rows x 2 columns]

In [117]:
df_cut = pd.cut(df['A'], np.arange(0,110,10))

In [118]:
df_cut

0      (40, 50]
1      (70, 80]
2      (40, 50]
3      (30, 40]
4      (70, 80]
        ...    
95     (50, 60]
96     (50, 60]
97     (80, 90]
98     (40, 50]
99    (90, 100]
Name: A, Length: 100, dtype: category
Categories (10, interval[int64, right]): [(0, 10] < (10, 20] < (20, 30] < (30, 40] ... (60, 70] < (70, 80] < (80, 90] < (90, 100]]

In [119]:
df['A'] = df_cut

In [120]:
df

A   B
0    (40, 50]  29
1    (70, 80]  22
2    (40, 50]  63
3    (30, 40]  43
4    (70, 80]  75
..        ...  ..
95   (50, 60]  87
96   (50, 60]  40
97   (80, 90]  19
98   (40, 50]  56
99  (90, 100]  94

[100 rows x 2 columns]

In [121]:
df.groupby('A')['B'].agg('sum')

A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
Name: B, dtype: int32

# Задача № 39

In [194]:
# Создайте список индексов столбцов и строк для 3 самых больших значений в предлагаемом датафрейме.

df = pd.DataFrame(np.random.RandomState(30).randint(1, 101, size=(8, 8)))

In [179]:
df

0   1   2   3   4   5   6   7
0  38  38  46  46  13  24   3  54
1  18  47   4  42   8  66  50  46
2  62  36  19  19  77  17   7  63
3  28  47  46  65  63  12  16  24
4  14  51  34  56  29  59  92  79
5  58  76  96  45  38  76  58  40
6  10  34  48  40  37  23  41  26
7  55  70  91  27  79  92  20  31

In [180]:
lst = []

In [181]:
for i in range(3):
    lst.append(df.unstack().idxmax())
    
    df.loc[df.unstack().idxmax()[-1], df.unstack().idxmax()[0]] = 0

    

In [192]:
[lst[1], lst[2], lst[0]]

[(5, 7), (6, 4), (2, 5)]

In [195]:
# ВНИМАНИЕ ПРАВИЛЬНЫЙ ОТВЕТ:

df.unstack().sort_values()[-3:].index.tolist()

[(5, 7), (6, 4), (2, 5)]

In [197]:
df.unstack().sort_values()

6  0     3
2  1     4
6  2     7
4  1     8
0  6    10
        ..
7  4    79
2  7    91
5  7    92
6  4    92
2  5    96
Length: 64, dtype: int32

# Задача № 40

In [2]:
# Создайте новый столбец patched_vals, который содержит те же значения, что и vals, 
# но отрицательные значения заменить средним значением группы.

In [2]:
df = pd.DataFrame({"vals": np.random.RandomState(31).randint(-30, 30, size=15), 
                   "grps": np.random.RandomState(31).choice(["A", "B"], 15)})

In [3]:
df

vals grps
0    -12    A
1     -7    B
2    -14    A
3      4    A
4     -7    A
5     28    B
6     -2    A
7     -1    A
8      8    A
9     -2    B
10    28    A
11    12    A
12    16    A
13   -24    A
14   -12    A

In [4]:
df['patched_vals'] = df['vals']

In [6]:
df1 = df[df['vals'] > 0]
df1

vals grps  patched_vals
3      4    A             4
5     28    B            28
8      8    A             8
10    28    A            28
11    12    A            12
12    16    A            16

In [7]:
df1.groupby(['grps'])['vals'].agg('mean')

grps
A    13.6
B    28.0
Name: vals, dtype: float64

In [8]:
df1.groupby(['grps'])['vals'].agg('mean')['A']

13.6

In [9]:
df1.groupby(['grps'])['vals'].agg('mean')['B']

28.0

In [10]:
df['patched_vals'] = np.where((df['patched_vals'] < 0) & (df['grps'] == 'A'),  df1.groupby(['grps'])['vals'].agg('mean').loc['A'], df['patched_vals'])

In [13]:
df['patched_vals'] = np.where((df['patched_vals'] < 0) & (df['grps'] == 'B'),  df1.groupby(['grps'])['vals'].agg('mean').loc['B'], df['patched_vals'])

In [ ]:
df

# Задача № 41

In [2]:
# Найдите сумму всех значений, которые указаны для среды (Wednesday)

dti = pd.date_range(start='2021-01-01', end='2021-12-31', freq='B') 
s = pd.Series(np.random.RandomState(30).rand(len(dti)), index=dti)

In [7]:
ss = s.to_frame().reset_index()

In [8]:
ss

index         0
0   2021-01-01  0.644144
1   2021-01-04  0.380748
2   2021-01-05  0.663048
3   2021-01-06  0.163651
4   2021-01-07  0.962608
..         ...       ...
256 2021-12-27  0.358708
257 2021-12-28  0.391431
258 2021-12-29  0.608953
259 2021-12-30  0.721118
260 2021-12-31  0.698055

[261 rows x 2 columns]

In [22]:
ss['index'].dt.day_name() == 'Wednesday'

0      False
1      False
2      False
3       True
4      False
       ...  
256    False
257    False
258     True
259    False
260    False
Name: index, Length: 261, dtype: bool

In [25]:
ss[ss['index'].dt.day_name() == 'Wednesday'].loc[:,0].sum()

23.508792429234397

In [ ]:
# Для каждого месяца найдите среднее значение.

In [ ]:
dti_1 = pd.date_range(start='2021-01-01', end='2021-12-31', freq='M')

In [72]:
dti_1

DatetimeIndex(['2021-01-31', '2021-02-28', '2021-03-31', '2021-04-30',
               '2021-05-31', '2021-06-30', '2021-07-31', '2021-08-31',
               '2021-09-30', '2021-10-31', '2021-11-30', '2021-12-31'],
              dtype='datetime64[ns]', freq='M')

In [30]:
ss['index'].dt.month

0       1
1       1
2       1
3       1
4       1
       ..
256    12
257    12
258    12
259    12
260    12
Name: index, Length: 261, dtype: int64

In [32]:
ss['month'] = ss['index'].dt.month

In [33]:
ss

index         0  month
0   2021-01-01  0.644144      1
1   2021-01-04  0.380748      1
2   2021-01-05  0.663048      1
3   2021-01-06  0.163651      1
4   2021-01-07  0.962608      1
..         ...       ...    ...
256 2021-12-27  0.358708     12
257 2021-12-28  0.391431     12
258 2021-12-29  0.608953     12
259 2021-12-30  0.721118     12
260 2021-12-31  0.698055     12

[261 rows x 3 columns]

In [47]:
sss = ss.groupby(['month'])[0].agg('mean')

In [61]:
sss = sss.to_frame()

In [64]:
sss = sss.set_index(dti_1)

In [66]:
sss[0]

2021-01-31    0.507726
2021-02-28    0.462692
2021-03-31    0.478605
2021-04-30    0.564210
2021-05-31    0.387735
2021-06-30    0.451999
2021-07-31    0.541958
2021-08-31    0.553241
2021-09-30    0.507650
2021-10-31    0.453517
2021-11-30    0.490528
2021-12-31    0.495812
Freq: M, Name: 0, dtype: float64

In [70]:
sss[0].name = None

In [71]:
sss[0]

2021-01-31    0.507726
2021-02-28    0.462692
2021-03-31    0.478605
2021-04-30    0.564210
2021-05-31    0.387735
2021-06-30    0.451999
2021-07-31    0.541958
2021-08-31    0.553241
2021-09-30    0.507650
2021-10-31    0.453517
2021-11-30    0.490528
2021-12-31    0.495812
Freq: M, dtype: float64

# Задача № 42

In [47]:
# Превратите датафрейм в квадрат с максимально возможной длиной стороны n, убрав отрицательные значения. 
# При необходимости удалите наименьшие значения. Порядок положительных чисел в результате должен оставаться 
# таким же, как и в оригинале.

# Подсказка:

# Шаг 1: Удалите отрицательные значения

# Шаг 2: Определите наибольший размер стороны квадрата n, который может получиться

# Шаг 3: Постройте квадрат со стороной n из ТОП n^2 наибольших значений

df = pd.DataFrame(np.random.RandomState(30).randint(-20, 50, 100).reshape(10,-1))

In [48]:
df

0   1   2   3   4   5   6   7   8   9
0  17  17  25  25  -8   3 -18  33  -3  26
1 -17  21 -13  45  29  25  41  15  -2  -2
2  -4 -14  42   7  26  25  44  42  -9  -5
3   3  -7  30  13  35   8  38  37  24  17
4  37  19 -11  13  27  19  16   2  20   5
5  34  49   6  -1  10  29  32  24  41  14
6  23   8  40  31  21  36  -4  19  13 -11
7  -9 -16   8 -10  -3  38 -11  25  28  35
8  -1  25  11   3  -9   9  24   9  -1  31
9  35  32   3  41 -14  19  10  24  27  -7

In [49]:
df_1 = df.values[df.values > 0]

In [50]:
df_1

array([17, 17, 25, 25,  3, 33, 26, 21, 45, 29, 25, 41, 15, 42,  7, 26, 25,
       44, 42,  3, 30, 13, 35,  8, 38, 37, 24, 17, 37, 19, 13, 27, 19, 16,
        2, 20,  5, 34, 49,  6, 10, 29, 32, 24, 41, 14, 23,  8, 40, 31, 21,
       36, 19, 13,  8, 38, 25, 28, 35, 25, 11,  3,  9, 24,  9, 31, 35, 32,
        3, 41, 19, 10, 24, 27])

In [51]:
len(df_1)

74

In [58]:
n = np.sqrt(len(df_1))//1

In [59]:
n

8.0

In [85]:
n = n.astype('int64')

In [61]:
r = len(df_1) - n**2

In [76]:
r = r.astype('int64')

In [77]:
r.dtype

dtype('int64')

In [69]:
df_1.min()

2

In [79]:
df_2 = list(df_1)

In [81]:
for _ in range(r):
    df_2.remove(min(df_2))    

In [83]:
len(df_2)

64

In [92]:
print(np.array(df_2).reshape(n, n).astype(np.float32))

[[17. 17. 25. 25. 33. 26. 21. 45.]
 [29. 25. 41. 15. 42. 26. 25. 44.]
 [42. 30. 13. 35. 38. 37. 24. 17.]
 [37. 19. 13. 27. 19. 16. 20. 34.]
 [49. 10. 29. 32. 24. 41. 14. 23.]
 [40. 31. 21. 36. 19. 13.  8. 38.]
 [25. 28. 35. 25. 11.  9. 24.  9.]
 [31. 35. 32. 41. 19. 10. 24. 27.]]


In [2]:
# Поменяйте местами строки 1 и 2

df = pd.DataFrame(np.arange(25).reshape(5, -1))

In [3]:
df

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [11]:
df = df.iloc[[0, 2, 1, 3, 4]]

In [13]:
df.index = [0, 1, 2, 3, 4]

In [14]:
df

0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24

In [2]:
# Измените порядок строк датафрейма таким образом, чтобы последние стали первыми, а первые последними (reverse).

In [3]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))

In [4]:
df

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [5]:
df[::-1]

0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4

In [6]:
# Выполните one-hot encoding для столбца А и добавьте результат к датафрейму

In [7]:
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))

In [8]:
df

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [16]:
df_1 = pd.get_dummies(df, columns = ['a'], prefix = '', prefix_sep='')

In [28]:
df_1

b   c   d   e  0  5  10  15  20
0   1   2   3   4  1  0   0   0   0
1   6   7   8   9  0  1   0   0   0
2  11  12  13  14  0  0   1   0   0
3  16  17  18  19  0  0   0   1   0
4  21  22  23  24  0  0   0   0   1

In [23]:
df_2 = df_1.drop(['b', 'c', 'd', 'e'], axis = 1 )

In [24]:
df_2

0  5  10  15  20
0  1  0   0   0   0
1  0  1   0   0   0
2  0  0   1   0   0
3  0  0   0   1   0
4  0  0   0   0   1

In [31]:
df_3 = df_2.merge(df.drop('a', axis = 1), left_index=True, right_index=True)

In [32]:
df_3

0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24

In [2]:
# Задача № 43

# Определите имя столбца с наибольшим количеством строковых максимумов. 

df = pd.DataFrame(np.random.RandomState(30).randint(1,100, 40).reshape(10, -1))


In [3]:
df

0   1   2   3
0  38  38  46  46
1  13  24   3  54
2  18  47   4  42
3   8  66  50  46
4  62  36  19  19
5  77  17   7  63
6  28  47  46  65
7  63  12  16  24
8  14  51  34  56
9  29  59  92  79

In [24]:
df.max(axis = 1)

46

In [38]:
df.iloc[0][0]

38

In [58]:
df.iloc[0]

0    38
1    38
2    46
3    46
Name: 0, dtype: int32

In [61]:
df.loc[0].max()

46

In [62]:
df.loc[i]

0    29
1    59
2    92
3    79
Name: 9, dtype: int32

In [34]:
df.max(axis = 1)[0]

46

In [37]:
df.iloc[0] == df.max(axis = 1)[0]

0    False
1    False
2     True
3     True
Name: 0, dtype: bool

In [63]:
a = []
for i in range(len(df)):
    for j in range(4):
        if df.iloc[i][j] == df.max(axis = 1)[i]:
            a.append(j)
        

In [67]:
j

3

In [64]:
b = pd.Series(a)    

In [65]:
b.value_counts().argmax()

0

In [66]:
b.value_counts() == b.value_counts().max()

3     True
0    False
2    False
1    False
dtype: bool

In [2]:
# b[b.value_counts() == b.value_counts().max()]

# Задача № 43

In [2]:
# Создайте новый столбец таким образом, чтобы каждая строка содержала номер 
# наиболее удалённой строки-записи по евклидову расстоянию.

In [177]:
df = pd.DataFrame(np.random.RandomState(30).randint(1,100, 40).reshape(10, -1))

In [178]:
df.index = list('abcdefghij')

In [179]:
df.columns = list('abcd')

In [180]:
df

a   b   c   d
a  38  38  46  46
b  13  24   3  54
c  18  47   4  42
d   8  66  50  46
e  62  36  19  19
f  77  17   7  63
g  28  47  46  65
h  63  12  16  24
i  14  51  34  56
j  29  59  92  79

In [174]:
df.iloc[0][0]

38

In [175]:
df.iloc[1][0]

13

In [176]:
df.loc[[ 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'a']]

a   b   c   d
b  13  24   3  54
c  18  47   4  42
d   8  66  50  46
e  62  36  19  19
f  77  17   7  63
g  28  47  46  65
h  63  12  16  24
i  14  51  34  56
j  29  59  92  79
a  38  38  46  46

In [79]:
new_df_index = list(df.index[1:])

In [84]:
new_df_index = new_df_index + [df.index[0]]

In [85]:
new_df_index

['b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'a']

In [24]:
np.sqrt((df.iloc[0][0] - df.iloc[1][0])**2 + (df.iloc[0][1] - df.iloc[1][1])**2 + (df.iloc[0][2] - df.iloc[1][2])**2   + (df.iloc[0][3] - df.iloc[1][3])**2)

52.28766584960549

In [153]:
df

a   b   c   d
a  38  38  46  46
b  13  24   3  54
c  18  47   4  42
d   8  66  50  46
e  62  36  19  19
f  77  17   7  63
g  28  47  46  65
h  63  12  16  24
i  14  51  34  56
j  29  59  92  79

In [185]:
ind = []
val_max = []

for i in range (10):

    y = len(df)
    x = 0
    i = 0
    a = []
    for x in range(y):

#         print(np.sqrt((df.iloc[i][0] - df.iloc[i + x][0])**2 + (df.iloc[i][1] - df.iloc[i + x][1])**2 + (df.iloc[i][2] - df.iloc[i + x][2])**2   + (df.iloc[i][3] - df.iloc[i + x][3])**2))
        a.append(np.sqrt((df.iloc[i][0] - df.iloc[i + x][0])**2 + (df.iloc[i][1] - df.iloc[i + x][1])**2 + (df.iloc[i][2] - df.iloc[i + x][2])**2   + (df.iloc[i][3] - df.iloc[i + x][3])**2))


        aa = pd.Series(a)
        x+=1


    b = aa.argmax()
    
    

    ind.append(df.index[b])
    val_max.append(max(a))

    new_df_index = list(df.index[1:])

    new_df_index = new_df_index + [df.index[0]]

    df = df.loc[new_df_index]
        
        
        

0.0
52.28766584960549
47.54997371187496
41.23105625617661
45.14421336118285
61.41661013113635
23.280893453645632
51.81698563212646
31.448370387032774
61.04916051838878
0.0
26.43860813280457
63.733821476512766
63.45076831686122
65.13063795173512
52.191953402799555
60.93439094632849
41.1703777004778
100.13490899781155
52.28766584960549
0.0
50.92150822589606
53.018864567246254
69.50539547402057
48.91829923454004
60.975404877704584
33.58571124749333
96.84007434941384
47.54997371187496
26.43860813280457
0.0
74.2024258363566
96.43650760992955
33.734255586866
87.06893820416096
24.839484696748443
57.81868210189506
41.23105625617661
63.733821476512766
50.92150822589606
0.0
51.633322573702344
64.20280367709809
24.71841418861655
64.21059102671458
102.69858811103491
45.14421336118285
63.45076831686122
53.018864567246254
74.2024258363566
0.0
69.46941773183363
42.69660408041839
76.83098333354845
107.46627377926528
61.41661013113635
65.13063795173512
69.50539547402057
96.43650760992955
51.63332257370

In [186]:
ind

['f', 'j', 'j', 'f', 'j', 'j', 'h', 'j', 'f', 'h']

In [188]:
val_max

[61.41661013113635,
 100.13490899781155,
 96.84007434941384,
 96.43650760992955,
 102.69858811103491,
 107.46627377926528,
 70.92954250522133,
 110.29959202100432,
 76.83098333354845,
 110.29959202100432]

In [189]:
df['nearest_row'] = ind

In [194]:
df['dist'] = np.round(np.array(val_max)).astype('int64')

In [195]:
df

a   b   c   d nearest_row  dist
a  38  38  46  46           f    61
b  13  24   3  54           j   100
c  18  47   4  42           j    97
d   8  66  50  46           f    96
e  62  36  19  19           j   103
f  77  17   7  63           j   107
g  28  47  46  65           h    71
h  63  12  16  24           j   110
i  14  51  34  56           f    77
j  29  59  92  79           h   110

# Задача №44

In [2]:
# Определите максимально возможное значение корреляции каждого столбца по сравнению с другими столбцами датафрейма.

df = pd.DataFrame(np.random.RandomState(25).randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))



In [3]:
df

p   q   r   s   t   u   v   w   x   y
a   5  63  91  16  62  24  45  51   9  29
b   5  90  32  70   2  40   4  89  56   4
c  85  46   4   2  23  32  49  48  74  17
d  51  86  37  10  33  11  61  48   2  87
e  92  50  19  93  37  99  31  39   3   6
f  58  74  23  12   3  44  91  62  85  84
g  75  18  15  84  38  88  51  52  15  72
h  63  91  16  15  77  40  89  47  54  30

In [13]:
df_1 = df.corr()

In [14]:
df_1

p         q         r         s         t         u         v  \
p  1.000000 -0.512107 -0.767901  0.139413  0.052365  0.544037  0.335403   
q -0.512107  1.000000  0.209535 -0.424986 -0.013054 -0.639377  0.142553   
r -0.767901  0.209535  1.000000 -0.187936  0.295132 -0.408626 -0.171527   
s  0.139413 -0.424986 -0.187936  1.000000 -0.152527  0.845489 -0.606281   
t  0.052365 -0.013054  0.295132 -0.152527  1.000000 -0.019302  0.319836   
u  0.544037 -0.639377 -0.408626  0.845489 -0.019302  1.000000 -0.210305   
v  0.335403  0.142553 -0.171527 -0.606281  0.319836 -0.210305  1.000000   
w -0.666213  0.391215  0.083154  0.150114 -0.619769 -0.215764 -0.430686   
x  0.036061  0.249027 -0.433272 -0.410009 -0.440047 -0.237842  0.308671   
y  0.113365 -0.049830 -0.013345 -0.297120 -0.114302 -0.184201  0.621780   

          w         x         y  
p -0.666213  0.036061  0.113365  
q  0.391215  0.249027 -0.049830  
r  0.083154 -0.433272 -0.013345  
s  0.150114 -0.410009 -0.297120  
t -0.619769 -0.440047 -0.114302  
u -0.215764 -0.237842 -0.184201  
v -0.430686  0.308671  0.621780  
w  1.000000  0.429285 -0.136803  
x  0.429285  1.000000 -0.058826  
y -0.136803 -0.058826  1.000000

In [31]:
np.round(sorted(abs(df_1.iloc[0]))[-2], 2)

0.77

In [68]:
lst = df_1.apply(lambda x: np.round(sorted(abs(x))[-2], 2)).values

In [82]:
lst

array([0.77, 0.64, 0.77, 0.85, 0.62, 0.85, 0.62, 0.67, 0.44, 0.62])

In [83]:
list(lst)

[0.77, 0.64, 0.77, 0.85, 0.62, 0.85, 0.62, 0.67, 0.44, 0.62]

In [84]:
print(lst)

[0.77 0.64 0.77 0.85 0.62 0.85 0.62 0.67 0.44 0.62]


# Задача №45

In [2]:
# Определите отношение минимума к максимуму для каждой строки.

df = pd.DataFrame(np.random.RandomState(25).randint(1,100, 80).reshape(8, -1))


In [3]:
df

0   1   2   3   4   5   6   7   8   9
0   5  63  91  16  62  24  45  51   9  29
1   5  90  32  70   2  40   4  89  56   4
2  85  46   4   2  23  32  49  48  74  17
3  51  86  37  10  33  11  61  48   2  87
4  92  50  19  93  37  99  31  39   3   6
5  58  74  23  12   3  44  91  62  85  84
6  75  18  15  84  38  88  51  52  15  72
7  63  91  16  15  77  40  89  47  54  30

In [13]:
df.loc[0]

0     5
1    63
2    91
3    16
4    62
5    24
6    45
7    51
8     9
9    29
Name: 0, dtype: int32

In [6]:
df.loc[0].max()

91

In [7]:
df.loc[0].min()

5

In [14]:
df.apply(lambda x: (x.min()/x.max()), axis = 1)

0    0.054945
1    0.022222
2    0.023529
3    0.022989
4    0.030303
5    0.032967
6    0.170455
7    0.164835
dtype: float64

# Задача №46

In [30]:
# Создайте новый столбец penultimate (с англ. предпоследний), который 
# имеет второе по величине значение каждой строки датафрейма:

df = pd.DataFrame(np.random.RandomState(25).randint(1,100, 80).reshape(8, -1))

In [31]:
df

0   1   2   3   4   5   6   7   8   9
0   5  63  91  16  62  24  45  51   9  29
1   5  90  32  70   2  40   4  89  56   4
2  85  46   4   2  23  32  49  48  74  17
3  51  86  37  10  33  11  61  48   2  87
4  92  50  19  93  37  99  31  39   3   6
5  58  74  23  12   3  44  91  62  85  84
6  75  18  15  84  38  88  51  52  15  72
7  63  91  16  15  77  40  89  47  54  30

In [32]:
sorted(df.loc[0])

[5, 9, 16, 24, 29, 45, 51, 62, 63, 91]

In [33]:
df['penultimate'] = df.apply(lambda x: sorted(x)[-2], axis = 1)

In [34]:
df

0   1   2   3   4   5   6   7   8   9  penultimate
0   5  63  91  16  62  24  45  51   9  29           63
1   5  90  32  70   2  40   4  89  56   4           89
2  85  46   4   2  23  32  49  48  74  17           74
3  51  86  37  10  33  11  61  48   2  87           86
4  92  50  19  93  37  99  31  39   3   6           93
5  58  74  23  12   3  44  91  62  85  84           85
6  75  18  15  84  38  88  51  52  15  72           84
7  63  91  16  15  77  40  89  47  54  30           89

# Задача №47

In [2]:
# Нормализуйте все столбцы датафрейма, вычитая среднее значение столбца и разделив на стандартное отклонение:

df = pd.DataFrame(np.random.RandomState(20).randint(1,100, 80).reshape(8, -1))



In [3]:
df

0   1   2   3   4   5   6   7   8   9
0  91  16  96  29  91  10  21  76  23  72
1  35  97  41  86  91  27  84  17  63  17
2   8  99   7  27  14  76  59  26   4  75
3  76  62  78  84  58  95  33  11   7  76
4  19   4  78  18  44  17  19  80  91  60
5  72  76  30  46   7  64  79  25  19  94
6  34  79  43  95   4  19  71  53  23  15
7   5  28  76   9   7  27  80  83  79  11

In [4]:
df.mean()

0    42.500
1    57.625
2    56.125
3    49.250
4    39.500
5    41.875
6    55.750
7    46.375
8    38.625
9    52.500
dtype: float64

In [7]:
df[0].std()

32.99783542684494

In [9]:
df.apply(lambda x: np.round((x-x.mean())/x.std(),2))

0     1     2     3     4     5     6     7     8     9
0  1.47 -1.13  1.31 -0.59  1.38 -1.00 -1.27  0.98 -0.46  0.59
1 -0.23  1.07 -0.50  1.08  1.38 -0.47  1.03 -0.97  0.72 -1.08
2 -1.05  1.12 -1.62 -0.65 -0.69  1.07  0.12 -0.67 -1.02  0.68
3  1.02  0.12  0.72  1.02  0.50  1.67 -0.83 -1.17 -0.93  0.71
4 -0.71 -1.45  0.72 -0.92  0.12 -0.78 -1.34  1.11  1.55  0.23
5  0.89  0.50 -0.86 -0.10 -0.87  0.70  0.85 -0.71 -0.58  1.26
6 -0.26  0.58 -0.43  1.34 -0.95 -0.72  0.56  0.22 -0.46 -1.14
7 -1.14 -0.80  0.66 -1.18 -0.87 -0.47  0.89  1.21  1.19 -1.26

In [10]:
df

0   1   2   3   4   5   6   7   8   9
0  91  16  96  29  91  10  21  76  23  72
1  35  97  41  86  91  27  84  17  63  17
2   8  99   7  27  14  76  59  26   4  75
3  76  62  78  84  58  95  33  11   7  76
4  19   4  78  18  44  17  19  80  91  60
5  72  76  30  46   7  64  79  25  19  94
6  34  79  43  95   4  19  71  53  23  15
7   5  28  76   9   7  27  80  83  79  11

# Задача № 48

In [2]:
# Для вас подготовлен датафрейм содержащий имена пользователей и их теги. 
# Ваша задача заключается в том чтобы вытянуть самый первый тег из списка 
# и сформировать отдельную колонку:

initial_df = pd.DataFrame({'user_name' : ['Ivan 007', 'Petr 911', 'Nikolay 112'], 'user_tags' : ["['sport', 'law', 'cars']", "['cars', 'law', 'girls']" ,"['law', 'travels', 'cars']"]})

In [3]:
initial_df

user_name                   user_tags
0     Ivan 007    ['sport', 'law', 'cars']
1     Petr 911    ['cars', 'law', 'girls']
2  Nikolay 112  ['law', 'travels', 'cars']

In [31]:
initial_df.user_tags.str.split("'")[0][1]

'sport'

In [41]:
initial_df['user_tags'].apply(lambda x: x.split("'")[1])

0    sport
1     cars
2      law
Name: user_tags, dtype: object

In [42]:
new_col = initial_df['user_tags'].apply(lambda x: x.split("'")[1])

In [43]:
initial_df['user_main_tag'] = new_col

In [44]:
initial_df

user_name                   user_tags user_main_tag
0     Ivan 007    ['sport', 'law', 'cars']         sport
1     Petr 911    ['cars', 'law', 'girls']          cars
2  Nikolay 112  ['law', 'travels', 'cars']           law

# Задача № 49

In [3]:
# Некоторые значения в столбце FlightNumber отсутствуют. Значения в столбце 
# должны увеличиваться на 10 с каждой строкой, поэтому в пропусках необходимо 
# установить 10055 и 10075. Заполните эти недостающие числа и измените тип столбца с float на int


initial_df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})

In [4]:
initial_df

From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"

In [6]:
initial_df['FlightNumber'] = initial_df['FlightNumber'].interpolate()

# Задача № 50

In [27]:
# Разбейте данные из столбца From_To на два столбца From и То. Исходный столбец удалите.

initial_df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})

In [3]:
initial_df

From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"

In [14]:
initial_df['From_To'].str.split('_')[0][0].title()

'London'

In [28]:
initial_df['From_To'].apply(lambda x: x.split('_')[0].title())

0      London
1      Madrid
2      London
3    Budapest
4    Brussels
Name: From_To, dtype: object

In [29]:
initial_df['From_To'].apply(lambda x: x.split('_')[1].title())

0        Paris
1        Milan
2    Stockholm
3        Paris
4       London
Name: From_To, dtype: object

In [30]:
initial_df['From'] = initial_df['From_To'].apply(lambda x: x.split('_')[0].title())

In [31]:
initial_df['To'] = initial_df['From_To'].apply(lambda x: x.split('_')[1].title())

In [33]:
df = initial_df.drop('From_To', axis = 1)

In [34]:
df

FlightNumber  RecentDelays              Airline      From         To
0       10045.0      [23, 47]               KLM(!)    London      Paris
1           NaN            []    <Air France> (12)    Madrid      Milan
2       10065.0  [24, 43, 87]  (British Airways. )    London  Stockholm
3           NaN          [13]       12. Air France  Budapest      Paris
4       10085.0      [67, 32]          "Swiss Air"  Brussels     London

# Задача № 51

In [ ]:
# В столбце Airline содержатся наименования авиакомпаний. 
# Можно заметить, что в названиях присутствуют 'лишние' символы. 
# Выполните преобразование столбца Airline:

In [28]:
initial_df

From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"

In [12]:
initial_df['Airline'][0].strip('(!)')

'KLM'

In [14]:
initial_df['Airline'].apply(lambda x: x.strip('"".12()! <>'))

0                KLM
1         Air France
2    British Airways
3         Air France
4          Swiss Air
Name: Airline, dtype: object

In [15]:
initial_df['Airline'] = initial_df['Airline'].apply(lambda x: x.strip('"".12()! <>'))

In [16]:
initial_df

From_To  FlightNumber  RecentDelays          Airline
0      LoNDon_paris       10045.0      [23, 47]              KLM
1      MAdrid_miLAN           NaN            []       Air France
2  londON_StockhOlm       10065.0  [24, 43, 87]  British Airways
3    Budapest_PaRis           NaN          [13]       Air France
4   Brussels_londOn       10085.0      [67, 32]        Swiss Air

# Задача № 52

In [402]:
# Распакуйте данные из RecentDelays по столбцам delay_1 ... delay_n. После распаковки удалите столбец RecentDelays.

initial_df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})

In [400]:

for i in range(len(initial_df)):
    
    col_num = 1
    
    for j in initial_df['RecentDelays'].iloc[i]:
        
        col_name = 'delay_' + str(col_num)

        initial_df[col_name] = np.nan
        initial_df[col_name].astype('float64')
        col_num += 1
        
        

In [401]:
initial_df.apply(pd.Series)

From_To  FlightNumber  RecentDelays              Airline  delay_1  \
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)      NaN   
1      MAdrid_miLAN           NaN            []    <Air France> (12)      NaN   
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )      NaN   
3    Budapest_PaRis           NaN          [13]       12. Air France      NaN   
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"      NaN   

   delay_2  delay_3  
0      NaN      NaN  
1      NaN      NaN  
2      NaN      NaN  
3      NaN      NaN  
4      NaN      NaN

In [377]:
df = initial_df.copy()

In [378]:
for i in range(len(initial_df)):
    
    col_num = 1
    
    for j in initial_df['RecentDelays'].iloc[i]:
        
        col_name = 'delay_' + str(col_num)
        
        
        initial_df[col_name] = j                
        
        
        df.iloc[i] = initial_df.iloc[i].copy()        

        col_num += 1
        
    initial_df[initial_df.columns[4:]] = np.nan     
        


In [379]:
df

From_To  FlightNumber  RecentDelays              Airline  delay_1  \
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)     23.0   
1      MAdrid_miLAN           NaN            []    <Air France> (12)      NaN   
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )     24.0   
3    Budapest_PaRis           NaN          [13]       12. Air France     13.0   
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"     67.0   

   delay_2  delay_3  
0     47.0      NaN  
1      NaN      NaN  
2     43.0     87.0  
3      NaN      NaN  
4     32.0      NaN

In [380]:
df = df.drop('RecentDelays', axis = 1)

In [381]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   From_To       5 non-null      object 
 1   FlightNumber  3 non-null      float64
 2   Airline       5 non-null      object 
 3   delay_1       4 non-null      float64
 4   delay_2       3 non-null      float64
 5   delay_3       1 non-null      float64
dtypes: float64(4), object(2)
memory usage: 368.0+ bytes


In [382]:
initial_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   From_To       5 non-null      object 
 1   FlightNumber  3 non-null      float64
 2   RecentDelays  5 non-null      object 
 3   Airline       5 non-null      object 
 4   delay_1       0 non-null      float64
 5   delay_2       0 non-null      float64
 6   delay_3       0 non-null      float64
dtypes: float64(4), object(3)
memory usage: 408.0+ bytes


In [403]:
import pandas as pd
import numpy as np

def solution(df):
    for i in range(len(initial_df)):
    
        col_num = 1
    
        for j in initial_df['RecentDelays'].iloc[i]:
        
            col_name = 'delay_' + str(col_num)

            initial_df[col_name] = np.nan
        
            col_num += 1
        
        
        
        
    df = initial_df.copy()
    
    
    
    
    
    for i in range(len(initial_df)):
    
        col_num = 1
    
        for j in initial_df['RecentDelays'].iloc[i]:
        
            col_name = 'delay_' + str(col_num)
        
        
            initial_df[col_name] = j                
        
        
            df.iloc[i] = initial_df.iloc[i].copy()        

            col_num += 1
        
        initial_df[initial_df.columns[4:]] = np.nan
    
    df = df.drop('RecentDelays', axis = 1)
    
    return df

In [405]:
solution(initial_df)

From_To  FlightNumber              Airline  delay_1  delay_2  \
0      LoNDon_paris       10045.0               KLM(!)     23.0     47.0   
1      MAdrid_miLAN           NaN    <Air France> (12)      NaN      NaN   
2  londON_StockhOlm       10065.0  (British Airways. )     24.0     43.0   
3    Budapest_PaRis           NaN       12. Air France     13.0      NaN   
4   Brussels_londOn       10085.0          "Swiss Air"     67.0     32.0   

   delay_3  
0      NaN  
1      NaN  
2     87.0  
3      NaN  
4      NaN

# Задача №53

In [458]:

# Замените на 0 все значения на диагоналях матрицы:

df = pd.DataFrame(np.random.RandomState(10).randint(1,100, 100).reshape(10, -1))
df

0   1   2   3   4   5   6   7   8   9
0  10  16  65  29  90  94  30   9  74   1
1  41  37  17  12  55  89  63  34  73  79
2  50  52  55  78  70  14  26  14  93  87
3  31  31  90  13  66  32  58  37  28  19
4  94  78  23  24  95  12  29  75  89  10
5  16  19  81  72  89  12  18  47   8  76
6  29  34  85  97  89  45   6   5  72  89
7  89  51  55  35  16  78  89  16   7  86
8  23  12  13  93  97  63  58  80  43  58
9  98  51  46  41  90  74  38   1  19  24

In [421]:
np.diag(df)

array([10, 37, 55, 13, 95, 12,  6, 16, 43, 24])

In [420]:
np.diag(np.array(df))

array([10, 37, 55, 13, 95, 12,  6, 16, 43, 24])

In [426]:
df.loc[0][1]

16

In [430]:
for i in df.columns:
    for j in df.index:
        if i == j:
            df.loc[i][j] = 0
            
            
            

In [431]:
df

0   1   2   3   4   5   6   7   8   9
0   0  16  65  29  90  94  30   9  74   1
1  41   0  17  12  55  89  63  34  73  79
2  50  52   0  78  70  14  26  14  93  87
3  31  31  90   0  66  32  58  37  28  19
4  94  78  23  24   0  12  29  75  89  10
5  16  19  81  72  89   0  18  47   8  76
6  29  34  85  97  89  45   0   5  72  89
7  89  51  55  35  16  78  89   0   7  86
8  23  12  13  93  97  63  58  80   0  58
9  98  51  46  41  90  74  38   1  19   0

In [455]:
a = len(df.columns)-1
b = 0

while b  < len(df.index):
    df.iloc[b][a] = 0
    a -= 1
    b += 1       


In [456]:
df

0   1   2   3   4   5   6   7   8   9
0   0  16  65  29  90  94  30   9  74   0
1  41   0  17  12  55  89  63  34   0  79
2  50  52   0  78  70  14  26   0  93  87
3  31  31  90   0  66  32   0  37  28  19
4  94  78  23  24   0   0  29  75  89  10
5  16  19  81  72   0   0  18  47   8  76
6  29  34  85   0  89  45   0   5  72  89
7  89  51   0  35  16  78  89   0   7  86
8  23   0  13  93  97  63  58  80   0  58
9   0  51  46  41  90  74  38   1  19   0

In [ ]:
# Внимание правильный ответ по диагоналям:
    

np.fill_diagonal(df.values, 0)
np.fill_diagonal(df.values[::-1], 0)

еще:
numpy.fill_diagonal устанавливает значения главной диагонали,
np.fliplr разворачивает матрицу зеркально

In [460]:
np.fill_diagonal(df.values, 0)

In [461]:
df

0   1   2   3   4   5   6   7   8   9
0   0  16  65  29  90  94  30   9  74   1
1  41   0  17  12  55  89  63  34  73  79
2  50  52   0  78  70  14  26  14  93  87
3  31  31  90   0  66  32  58  37  28  19
4  94  78  23  24   0  12  29  75  89  10
5  16  19  81  72  89   0  18  47   8  76
6  29  34  85  97  89  45   0   5  72  89
7  89  51  55  35  16  78  89   0   7  86
8  23  12  13  93  97  63  58  80   0  58
9  98  51  46  41  90  74  38   1  19   0

In [462]:
np.fill_diagonal(np.fliplr(df), 0)

In [463]:
df

0   1   2   3   4   5   6   7   8   9
0   0  16  65  29  90  94  30   9  74   0
1  41   0  17  12  55  89  63  34   0  79
2  50  52   0  78  70  14  26   0  93  87
3  31  31  90   0  66  32   0  37  28  19
4  94  78  23  24   0   0  29  75  89  10
5  16  19  81  72   0   0  18  47   8  76
6  29  34  85   0  89  45   0   5  72  89
7  89  51   0  35  16  78  89   0   7  86
8  23   0  13  93  97  63  58  80   0  58
9   0  51  46  41  90  74  38   1  19   0

# Задача № 54

In [75]:
# Создайте два новых столбца, один из которых является lag1 (сдвиг значений столбца А вниз на 1 строку), 
# а другой — lead1 (сдвиг значений столбца B вверх на 1 строку):
    
df = pd.DataFrame(np.random.RandomState(10).randint(1, 100, 20).reshape(-1, 4), columns = list('abcd'))

In [76]:
df

a   b   c   d
0  10  16  65  29
1  90  94  30   9
2  74   1  41  37
3  17  12  55  89
4  63  34  73  79

In [65]:
# list(df.a)

[10, 90, 74, 17, 63]

In [66]:
# lst = [np.nan]

In [67]:
# lst = lst + (list(df.a)[:-1])

In [68]:
# lst

[nan, 10, 90, 74, 17]

In [69]:
# lst_b = (list(df.b)[1:]) + [np.nan]

In [70]:
# lst_b

[94, 1, 12, 34, nan]

In [72]:
df['a_lag_1'] = [np.nan] + (list(df.a)[:-1])

In [73]:
df['b_lead_1'] = (list(df.b)[1:]) + [np.nan]

In [74]:
df

a   b   c   d  a_lag_1  b_lead_1
0  10  16  65  29      NaN      94.0
1  90  94  30   9     10.0       1.0
2  74   1  41  37     90.0      12.0
3  17  12  55  89     74.0      34.0
4  63  34  73  79     17.0       NaN

In [79]:
# Правильно через shift:

df['a'].shift(1)

0     NaN
1    10.0
2    90.0
3    74.0
4    17.0
Name: a, dtype: float64

In [80]:
df['b'].shift(-1)

0    94.0
1     1.0
2    12.0
3    34.0
4     NaN
Name: b, dtype: float64

# Задача № 55

In [187]:
# Сложность: 💪💪💪

# В исходном датафрейме содержится информация о затратах во время командировок по 
# каждому месяцу для каждого сотрудника. Выполните преобразование датафрейма:

df = pd.DataFrame({'city' : ['Moscow', 'Berlin', 'Paris'], 'agent' : ['Ivan', 'Valter', 'Ali Abu'],  'Jan-2022' : [5000, 3000, 2000], 'Feb-2022' : [3000, 2000, 4000], 'March-2022' : [0, 5000, 7000] })

In [188]:
df

city    agent  Jan-2022  Feb-2022  March-2022
0  Moscow     Ivan      5000      3000           0
1  Berlin   Valter      3000      2000        5000
2   Paris  Ali Abu      2000      4000        7000

In [189]:
df = pd.melt(df, id_vars = ['city', 'agent'])

In [190]:
df.columns = ['city', 'agent', 'Date', 'Value']

In [191]:
df

city    agent        Date  Value
0  Moscow     Ivan    Jan-2022   5000
1  Berlin   Valter    Jan-2022   3000
2   Paris  Ali Abu    Jan-2022   2000
3  Moscow     Ivan    Feb-2022   3000
4  Berlin   Valter    Feb-2022   2000
5   Paris  Ali Abu    Feb-2022   4000
6  Moscow     Ivan  March-2022      0
7  Berlin   Valter  March-2022   5000
8   Paris  Ali Abu  March-2022   7000

In [142]:
# Something about melt

df = pd.DataFrame({'A': {0: 'a', 1: 'b', 2: 'c'},
                   'B': {0: 1, 1: 3, 2: 5},
                   'C': {0: 2, 1: 4, 2: 6}})
df

A  B  C
0  a  1  2
1  b  3  4
2  c  5  6

In [143]:
pd.melt(df, id_vars=['A'], value_vars=['B'])

A variable  value
0  a        B      1
1  b        B      3
2  c        B      5

# Задача № 56

In [374]:
# Для каждого месяца определите, кто затратил больше всего денег:

df = pd.DataFrame({'city' : ['Moscow', 'Berlin', 'Paris'], 'agent' : ['Ivan', 'Valter', 'Ali Abu'],  'Jan-2022' : [5000, 3000, 2000], 'Feb-2022' : [3000, 2000, 4000], 'March-2022' : [0, 5000, 7000] }).melt(id_vars=["city", "agent"], var_name="Date", value_name="Value")
df = df.reset_index()
df

index    city    agent        Date  Value
0      0  Moscow     Ivan    Jan-2022   5000
1      1  Berlin   Valter    Jan-2022   3000
2      2   Paris  Ali Abu    Jan-2022   2000
3      3  Moscow     Ivan    Feb-2022   3000
4      4  Berlin   Valter    Feb-2022   2000
5      5   Paris  Ali Abu    Feb-2022   4000
6      6  Moscow     Ivan  March-2022      0
7      7  Berlin   Valter  March-2022   5000
8      8   Paris  Ali Abu  March-2022   7000

In [375]:
df_1 = df.groupby(['Date'])['Value'].agg('max').to_frame()

In [376]:
df_1

Value
Date             
Feb-2022     4000
Jan-2022     5000
March-2022   7000

In [377]:
df_2 = df.merge(df_1, on = ['Date', 'Value'])

In [378]:
df_2

index    city    agent        Date  Value
0      0  Moscow     Ivan    Jan-2022   5000
1      5   Paris  Ali Abu    Feb-2022   4000
2      8   Paris  Ali Abu  March-2022   7000

In [379]:
df_3 = df_2.set_index(df_2['index'])

In [380]:
df_3

index    city    agent        Date  Value
index                                           
0          0  Moscow     Ivan    Jan-2022   5000
5          5   Paris  Ali Abu    Feb-2022   4000
8          8   Paris  Ali Abu  March-2022   7000

In [381]:
# !!! Лёгкий способ сбросить мультииндексы и название индекса при set_index !!!

df_3.rename_axis(None)

index    city    agent        Date  Value
0      0  Moscow     Ivan    Jan-2022   5000
5      5   Paris  Ali Abu    Feb-2022   4000
8      8   Paris  Ali Abu  March-2022   7000

In [382]:
df_3

index    city    agent        Date  Value
index                                           
0          0  Moscow     Ivan    Jan-2022   5000
5          5   Paris  Ali Abu    Feb-2022   4000
8          8   Paris  Ali Abu  March-2022   7000

In [298]:
df_3 = df_2.set_index('index')

In [306]:
df_3.index.nameFalse

In [307]:
df_3

city    agent        Date  Value
False                                    
0      Moscow     Ivan    Jan-2022   5000
5       Paris  Ali Abu    Feb-2022   4000
8       Paris  Ali Abu  March-2022   7000